site_name: MethylPipeline Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Deployment: DEPLOYMENT.md
  - Theory Book Source: theory/README.md
