-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "Contract";

CREATE TABLE IF NOT EXISTS "Contract"."ContractLimits" (
  "ContractLimitID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ContractID" integer NOT NULL,
  "ScopeID" integer NULL,
  "MaxActiveUsers" integer NULL,
  "MaxStorageGB" numeric(18,2) NULL,
  "MaxRunsPerMonth" integer NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Contract_ContractLimits" PRIMARY KEY ("ContractLimitID")
);

CREATE TABLE IF NOT EXISTS "Contract"."ContractRolePolicies" (
  "ContractID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  "GrantTypeAllowed" varchar(16) NOT NULL,
  "MaxUsersForRole" integer NULL,
  "RequiresApproval" boolean NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Contract_ContractRolePolicies" PRIMARY KEY ("ContractID", "RoleID")
);

CREATE TABLE IF NOT EXISTS "Contract"."Contracts" (
  "ContractID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "CustomerID" integer NOT NULL,
  "Name" varchar(200) NOT NULL,
  "Status" varchar(24) NOT NULL,
  "StartDateUtc" timestamptz NOT NULL,
  "EndDateUtc" timestamptz NULL,
  "PlanCode" varchar(64) NULL,
  "BillingCycle" varchar(16) NULL,
  "AutoRenew" boolean NOT NULL,
  "TermsVersion" varchar(32) NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  "UpdatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Contract_Contracts" PRIMARY KEY ("ContractID")
);

CREATE TABLE IF NOT EXISTS "Contract"."ContractScopes" (
  "ContractID" integer NOT NULL,
  "ScopeID" integer NOT NULL,
  "Status" varchar(24) NOT NULL,
  "ActivatedAtUtc" timestamptz NOT NULL,
  "EffectiveFromUtc" timestamptz NOT NULL,
  "EffectiveToUtc" timestamptz NULL,
  CONSTRAINT "PK_Contract_ContractScopes" PRIMARY KEY ("ContractID", "ScopeID")
);

CREATE TABLE IF NOT EXISTS "Contract"."ContractWorkflowEntitlements" (
  "ContractID" integer NOT NULL,
  "WorkflowDefID" bigint NOT NULL,
  "Enabled" boolean NOT NULL,
  "MaxRunsPerPeriod" integer NULL,
  "PeriodType" varchar(8) NULL,
  "MaxConcurrentRuns" integer NULL,
  "DataRetentionDays" integer NULL,
  "SlaTier" varchar(32) NULL,
  "SupportTier" varchar(32) NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Contract_ContractWorkflowEntitlements" PRIMARY KEY ("ContractID", "WorkflowDefID")
);

CREATE TABLE IF NOT EXISTS "Contract"."WorkflowUsageCounters" (
  "ContractID" integer NOT NULL,
  "ScopeID" integer NOT NULL,
  "WorkflowDefID" bigint NOT NULL,
  "PeriodType" varchar(8) NOT NULL,
  "PeriodStartUtc" timestamptz NOT NULL,
  "RunsExecuted" integer NOT NULL,
  "UpdatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Contract_WorkflowUsageCounters" PRIMARY KEY ("ContractID", "ScopeID", "WorkflowDefID", "PeriodType", "PeriodStartUtc")
);

