-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "e_portal";

CREATE TABLE IF NOT EXISTS "e_portal"."AppRole2Node" (
  "AppRoleId" integer NOT NULL,
  "NodeId" integer NOT NULL,
  CONSTRAINT "PK_e_portal_AppRole2Node" PRIMARY KEY ("AppRoleId", "NodeId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."AppRole2Roles" (
  "RoleId" integer NOT NULL,
  "AppRoleId" smallint NOT NULL,
  CONSTRAINT "PK_e_portal_AppRole2Roles" PRIMARY KEY ("AppRoleId", "RoleId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."AppRoles" (
  "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "AppRole" varchar(128) NOT NULL,
  CONSTRAINT "PK_e_portal_AppRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "e_portal"."DMDataSetDef" (
  "DMDataSetDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DMKey" varchar(100) NOT NULL,
  "DataSetKey" varchar(100) NOT NULL,
  "SourceType" varchar(20) NOT NULL,
  "SourceName" varchar(500) NOT NULL,
  "SourceColumns" varchar(500) NULL,
  "SourceWhere" varchar(500) NULL,
  "SourceOrderBy" varchar(200) NULL,
  "Role" varchar(20) NOT NULL,
  "Seq" integer NOT NULL,
  CONSTRAINT "PK_e_portal_DMDataSetDef" PRIMARY KEY ("DMDataSetDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."DMDef" (
  "DMDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DMKey" varchar(100) NOT NULL,
  "Title" varchar(200) NULL,
  "IsActive" boolean NOT NULL,
  CONSTRAINT "PK_e_portal_DMDef" PRIMARY KEY ("DMDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."DMParamDef" (
  "DMParamDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DMKey" varchar(100) NOT NULL,
  "DataSetKey" varchar(100) NOT NULL,
  "ParamName" varchar(100) NOT NULL,
  "ParamSource" varchar(100) NULL,
  "DefaultValue" varchar(200) NULL,
  CONSTRAINT "PK_e_portal_DMParamDef" PRIMARY KEY ("DMParamDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."DMRelationDef" (
  "DMRelationDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DMKey" varchar(100) NOT NULL,
  "MasterDataSetKey" varchar(100) NOT NULL,
  "DetailDataSetKey" varchar(100) NOT NULL,
  "MasterField" varchar(100) NOT NULL,
  "DetailParam" varchar(100) NOT NULL,
  CONSTRAINT "PK_e_portal_DMRelationDef" PRIMARY KEY ("DMRelationDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."EPSessions" (
  "uniSessionId" varchar(50) NOT NULL,
  "sqlSessionId" integer NOT NULL,
  "StartDate" timestamptz NULL,
  "EndDate" timestamptz NULL,
  "UserId" bigint NULL,
  "ClientQty" integer NULL,
  CONSTRAINT "PK_e_portal_EPSessions" PRIMARY KEY ("uniSessionId", "sqlSessionId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."FrameDef" (
  "FrameDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FrameKey" varchar(100) NOT NULL,
  "MasterStoredProc" varchar(200) NOT NULL,
  "Title" varchar(200) NULL,
  "IdField" varchar(100) NULL,
  "IsActive" boolean NOT NULL,
  "FrameType" varchar(20) NOT NULL,
  "DMKey" varchar(100) NULL,
  CONSTRAINT "PK_e_portal_FrameDef" PRIMARY KEY ("FrameDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."FrameDimensionDef" (
  "FrameDimensionDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FrameKey" varchar(100) NOT NULL,
  "Caption" varchar(100) NOT NULL,
  "StoredProc" varchar(200) NOT NULL,
  "ParamName" varchar(100) NOT NULL,
  "ParamSource" varchar(100) NOT NULL,
  "DimOrder" integer NOT NULL,
  CONSTRAINT "PK_e_portal_FrameDimensionDef" PRIMARY KEY ("FrameDimensionDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."FrameFilterDef" (
  "FrameFilterDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FrameKey" varchar(100) NOT NULL,
  "FieldName" varchar(100) NOT NULL,
  "Caption" varchar(100) NOT NULL,
  "FilterOrder" integer NOT NULL,
  CONSTRAINT "PK_e_portal_FrameFilterDef" PRIMARY KEY ("FrameFilterDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."FramePanelDef" (
  "FramePanelDefId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FrameKey" varchar(100) NOT NULL,
  "PanelKey" varchar(100) NOT NULL,
  "Title" varchar(200) NULL,
  "PanelType" varchar(20) NOT NULL,
  "Region" varchar(20) NOT NULL,
  "DMKey" varchar(100) NULL,
  "DataSetKey" varchar(100) NULL,
  "RegionSize" integer NULL,
  "Seq" integer NOT NULL,
  CONSTRAINT "PK_e_portal_FramePanelDef" PRIMARY KEY ("FramePanelDefId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."NavTree" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ParentID" integer NULL,
  "Caption" varchar(50) NOT NULL,
  "Seq" smallint NOT NULL,
  "InfoID" integer NULL,
  CONSTRAINT "PK_e_portal_NavTree" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "e_portal"."NodeInfos" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "Singleton" boolean NOT NULL,
  "TypeId" smallint NULL,
  "FrameKey" varchar(100) NULL,
  CONSTRAINT "PK_e_portal_NodeInfos" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "e_portal"."Roles" (
  "RoleId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  CONSTRAINT "PK_e_portal_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."SyUsers" (
  "UserId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FullName" varchar(100) NOT NULL,
  "Email" varchar(50) NOT NULL,
  "Active" integer NOT NULL,
  "username" varchar(50) NULL,
  CONSTRAINT "PK_e_portal_SyUsers" PRIMARY KEY ("UserId")
);

CREATE TABLE IF NOT EXISTS "e_portal"."UserRoles" (
  "UserId" bigint NOT NULL,
  "RoleId" integer NOT NULL,
  CONSTRAINT "PK_e_portal_UserRoles" PRIMARY KEY ("UserId", "RoleId")
);

