-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "Meta";

CREATE TABLE IF NOT EXISTS "Meta"."Classes" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "TableName" varchar(64) NULL,
  "ParentID" integer NULL,
  "HasHistory" boolean NULL,
  CONSTRAINT "PK_Meta_Classes" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."CollectionItem" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "CollectionID" integer NOT NULL,
  "ParentID" integer NULL,
  "Idx" integer NULL,
  "ValueString" varchar(64) NULL,
  "ValueNumber" numeric(38,10) NULL,
  "ValueObjectID" integer NULL,
  CONSTRAINT "PK_Meta_CollectionItem" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."CollectionItemValue" (
  "CollectionItemID" integer NOT NULL,
  "Name" varchar(64) NOT NULL,
  "ValueType" varchar(1) NOT NULL,
  "ValueString" varchar(400) NULL,
  "ValueNumber" numeric(38,10) NULL,
  "ValueDate" timestamptz NULL,
  "ValueBit" boolean NULL,
  CONSTRAINT "PK_Meta_CollectionItemValue" PRIMARY KEY ("CollectionItemID", "Name")
);

CREATE TABLE IF NOT EXISTS "Meta"."Collections" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(200) NOT NULL,
  "Type" varchar(1) NOT NULL,
  "ItemClassID" integer NULL,
  "ValueType" varchar(1) NOT NULL,
  CONSTRAINT "PK_Meta_Collections" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."Event" (
  "ID" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(32) NOT NULL,
  CONSTRAINT "PK_Meta_Event" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."Links" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(64) NOT NULL,
  "ClassID1" integer NOT NULL,
  "ClassID2" integer NOT NULL,
  "LinkTypeID" smallint NOT NULL,
  "MinIdx2" integer NULL,
  "MaxIdx2" integer NULL,
  "Indexed" boolean NULL,
  "Owns" boolean NULL,
  CONSTRAINT "PK_Meta_Links" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."LinkTypes" (
  "ID" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(32) NOT NULL,
  CONSTRAINT "PK_Meta_LinkTypes" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."Objs" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ClassID" integer NOT NULL,
  CONSTRAINT "PK_Meta_Objs" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Meta"."Operations" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(100) NOT NULL,
  "ClassID" integer NOT NULL,
  CONSTRAINT "PK_Meta_Operations" PRIMARY KEY ("ID")
);

