-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "Onboarding";

CREATE TABLE IF NOT EXISTS "Onboarding"."ApprovalQueue" (
  "ApprovalID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InvitationID" bigint NOT NULL,
  "RequestedRoleID" integer NOT NULL,
  "RequestedGrantType" varchar(16) NOT NULL,
  "Status" varchar(16) NOT NULL,
  "ReviewedByUserID" integer NULL,
  "ReviewedAtUtc" timestamptz NULL,
  "ReviewComment" varchar(500) NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Onboarding_ApprovalQueue" PRIMARY KEY ("ApprovalID")
);

CREATE TABLE IF NOT EXISTS "Onboarding"."AuditLog" (
  "AuditID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ScopeID" integer NULL,
  "InvitationID" bigint NULL,
  "ActorUserID" integer NULL,
  "EventType" varchar(64) NOT NULL,
  "EventDataJson" jsonb NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Onboarding_AuditLog" PRIMARY KEY ("AuditID")
);

CREATE TABLE IF NOT EXISTS "Onboarding"."InvitationBatches" (
  "BatchID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ScopeID" integer NOT NULL,
  "CreatedByUserID" integer NOT NULL,
  "Status" varchar(16) NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Onboarding_InvitationBatches" PRIMARY KEY ("BatchID")
);

CREATE TABLE IF NOT EXISTS "Onboarding"."Invitations" (
  "InvitationID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "BatchID" bigint NULL,
  "ScopeID" integer NOT NULL,
  "Email" varchar(255) NOT NULL,
  "ExpectedProviderID" integer NOT NULL,
  "ExpectedDomain" varchar(255) NULL,
  "DefaultRoleID" integer NULL,
  "GrantType" varchar(16) NOT NULL,
  "ExpiresAtUtc" timestamptz NOT NULL,
  "Status" varchar(16) NOT NULL,
  "AcceptedByUserID" integer NULL,
  "AcceptedAtUtc" timestamptz NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_Onboarding_Invitations" PRIMARY KEY ("InvitationID")
);

