-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "portal";

-- Lowercase synonym schema not created; use quoted portal."Samples".

CREATE TABLE IF NOT EXISTS "portal"."Batches" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NULL,
  "LabID" integer NULL,
  CONSTRAINT "PK_portal_Batches" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."CustomerInstitutions" (
  "CustomerID" integer NOT NULL,
  "InstitutionID" integer NOT NULL,
  CONSTRAINT "PK_portal_CustomerInstitutions" PRIMARY KEY ("CustomerID", "InstitutionID")
);

CREATE TABLE IF NOT EXISTS "portal"."Customers" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(100) NOT NULL,
  CONSTRAINT "PK_portal_Customers" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."DiseaseDataSource" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DiseaseID" integer NOT NULL,
  "SourceType" varchar(20) NOT NULL,
  "SourceObject" varchar(128) NOT NULL,
  "SubtypeTable" varchar(128) NULL,
  "KeyField" varchar(128) NOT NULL,
  "CustomerParamName" varchar(128) NOT NULL,
  "DiseaseParamName" varchar(128) NOT NULL,
  "IsActive" boolean NOT NULL,
  "CreatedAt" timestamptz NOT NULL,
  "UpdatedAt" timestamptz NOT NULL,
  CONSTRAINT "PK_portal_DiseaseDataSource" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."DiseaseFieldContract" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DiseaseID" integer NOT NULL,
  "FieldName" varchar(128) NOT NULL,
  "FieldCaption" varchar(128) NOT NULL,
  "DataType" varchar(20) NOT NULL,
  "IsBaseField" boolean NOT NULL,
  "DisplayOrder" integer NOT NULL,
  "ColumnWidth" integer NOT NULL,
  "IsVisible" boolean NOT NULL,
  "IsFilterable" boolean NOT NULL,
  "FilterOperatorDefault" varchar(20) NOT NULL,
  "FilterEditorKind" varchar(20) NOT NULL,
  "IsSortable" boolean NOT NULL,
  "IsEditable" boolean NOT NULL,
  "IsRequired" boolean NOT NULL,
  "ValidationJson" text NULL,
  "LookupQuery" text NULL,
  "TargetEntity" varchar(20) NOT NULL,
  "TargetColumn" varchar(128) NULL,
  "CollectionName" varchar(200) NULL,
  "ValueStoreMode" varchar(20) NULL,
  "MergeStrategy" varchar(20) NULL,
  "IsActive" boolean NOT NULL,
  "CreatedAt" timestamptz NOT NULL,
  "UpdatedAt" timestamptz NOT NULL,
  CONSTRAINT "PK_portal_DiseaseFieldContract" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."Diseases" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "ParentID" integer NULL,
  CONSTRAINT "PK_portal_Diseases" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."Groups" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "Description" varchar(256) NULL,
  "CustomerID" integer NULL,
  CONSTRAINT "PK_portal_Groups" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."GroupSamples" (
  "GroupID" integer NOT NULL,
  "SampleID" integer NOT NULL,
  CONSTRAINT "PK_portal_GroupSamples" PRIMARY KEY ("GroupID", "SampleID")
);

CREATE TABLE IF NOT EXISTS "portal"."InstitutionLabs" (
  "InstitutionID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "LabID" integer NOT NULL,
  CONSTRAINT "PK_portal_InstitutionLabs" PRIMARY KEY ("InstitutionID", "LabID")
);

CREATE TABLE IF NOT EXISTS "portal"."Institutions" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  CONSTRAINT "PK_portal_Institutions" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."Labs" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  CONSTRAINT "PK_portal_Labs" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."LabSamples" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "SampleID" integer NOT NULL,
  "BatchID" integer NULL,
  "Sample" varchar(128) NULL,
  "AlignmentQC" jsonb NULL,
  CONSTRAINT "PK_portal_LabSamples" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."NavTree" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ParentID" integer NULL,
  "Caption" varchar(50) NOT NULL,
  "Seq" smallint NOT NULL,
  "InfoID" integer NULL,
  "NodePath" varchar(2048) NULL,
  "SortPath" varchar(2048) NULL,
  CONSTRAINT "PK_portal_NavTree" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."NodeInfos" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "Singleton" boolean NOT NULL,
  "TypeId" smallint NULL,
  "FrameKey" varchar(100) NULL,
  CONSTRAINT "PK_portal_NodeInfos" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "portal"."Objs" (
  "ObjID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "MetaObjID" integer NOT NULL,
  CONSTRAINT "PK_portal_Objs" PRIMARY KEY ("ObjID", "MetaObjID")
);

CREATE TABLE IF NOT EXISTS "portal"."Patients" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "InstitutionID" integer NULL,
  "Name" varchar(50) NOT NULL,
  "Sex" varchar(1) NULL,
  "YearBorn" integer NULL,
  "Race" varchar(50) NULL,
  "Ethnicity" varchar(50) NULL,
  "ExternalID" varchar(64) NULL,
  CONSTRAINT "PK_portal_Patients" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."project" (
  "project_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" integer NOT NULL,
  "project_key" varchar(64) NOT NULL,
  "display_name" varchar(128) NOT NULL,
  "project_path" varchar(512) NOT NULL,
  "archive_profile_key" varchar(64) NOT NULL,
  "status" varchar(32) NOT NULL,
  "created_at_utc" timestamptz NOT NULL,
  "updated_at_utc" timestamptz NULL,
  CONSTRAINT "PK_portal_project" PRIMARY KEY ("project_id")
);

CREATE TABLE IF NOT EXISTS "portal"."Role2Node" (
  "RoleId" integer NOT NULL,
  "NodeId" integer NOT NULL,
  "ScopeId" integer NOT NULL,
  CONSTRAINT "PK_portal_Role2Node" PRIMARY KEY ("ScopeId", "RoleId", "NodeId")
);

CREATE TABLE IF NOT EXISTS "portal"."UserRoles" (
  "UserId" bigint NOT NULL,
  "RoleId" integer NOT NULL,
  CONSTRAINT "PK_portal_UserRoles" PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS "portal"."SampleImportBatch" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "DiseaseID" integer NOT NULL,
  "CustomerID" integer NOT NULL,
  "InstitutionID" integer NOT NULL,
  "CreatedBy" integer NULL,
  "FileName" varchar(260) NULL,
  "FileHash" bytea NULL,
  "Status" varchar(20) NOT NULL,
  "Mode" varchar(20) NOT NULL,
  "MappingJson" text NULL,
  "RowCount" integer NOT NULL,
  "CreatedAt" timestamptz NOT NULL,
  "UpdatedAt" timestamptz NOT NULL,
  CONSTRAINT "PK_portal_SampleImportBatch" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."SampleImportRow" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "BatchID" integer NOT NULL,
  "RowNo" integer NOT NULL,
  "RawJson" text NULL,
  "CanonicalJson" text NULL,
  "Status" varchar(20) NOT NULL,
  "ErrorsJson" text NULL,
  "ConflictsJson" text NULL,
  "Action" varchar(20) NULL,
  "CreatedPatientID" integer NULL,
  "CreatedSampleID" integer NULL,
  CONSTRAINT "PK_portal_SampleImportRow" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."Samples" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "PatientID" integer NOT NULL,
  "CustomerID" integer NULL,
  "SampleName" varchar(128) NULL,
  "Age" integer NULL,
  "Height" integer NULL,
  "Weight" integer NULL,
  "BMI" double precision NULL,
  "DiseaseID" integer NULL,
  "Stage" varchar(50) NULL,
  "Extras" jsonb NULL,
  "analyte_id" bigint NULL,
  CONSTRAINT "PK_portal_Samples" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."SamplesBreastCancer" (
  "ID" integer NOT NULL,
  "ER_Status" boolean NULL,
  "PR_Status" boolean NULL,
  "HER2_Status" boolean NULL,
  CONSTRAINT "PK_portal_SamplesBreastCancer" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "portal"."SamplesProstateCancer" (
  "ID" integer NOT NULL,
  "PSA" double precision NULL,
  "DRE" boolean NULL,
  "GleasonScore" varchar(10) NULL,
  CONSTRAINT "PK_portal_SamplesProstateCancer" PRIMARY KEY ("ID")
);

