-- Auto-generated by scripts/generate_pg_clinical_ddl.py
-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.
-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.

CREATE SCHEMA IF NOT EXISTS "RBAC";

CREATE TABLE IF NOT EXISTS "RBAC"."BypassScopeApprovals" (
  "ApprovalID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "UserID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  "RequestedByUserID" integer NOT NULL,
  "ApprovedByUserID" integer NULL,
  "Status" varchar(16) NOT NULL,
  "Reason" varchar(500) NOT NULL,
  "TicketRef" varchar(128) NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  "ApprovedAtUtc" timestamptz NULL,
  "ExpiresAtUtc" timestamptz NULL,
  CONSTRAINT "PK_RBAC_BypassScopeApprovals" PRIMARY KEY ("ApprovalID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."ExternalIdentities" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "UserID" integer NOT NULL,
  "ProviderID" integer NOT NULL,
  "Subject" varchar(512) NOT NULL,
  "EmailSnapshot" varchar(255) NULL,
  "Active" boolean NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  "LastLoginAtUtc" timestamptz NULL,
  CONSTRAINT "PK_RBAC_ExternalIdentities" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Group_Roles" (
  "GroupID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  CONSTRAINT "PK_RBAC_Group_Roles" PRIMARY KEY ("GroupID", "RoleID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Group_Users" (
  "GroupID" integer NOT NULL,
  "UserID" integer NOT NULL,
  "AddedAt" timestamptz NOT NULL,
  CONSTRAINT "PK_RBAC_Group_Users" PRIMARY KEY ("GroupID", "UserID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Groups" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(200) NOT NULL,
  CONSTRAINT "PK_RBAC_Groups" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."IdentityProviders" (
  "ProviderID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(128) NOT NULL,
  "ProviderType" varchar(32) NOT NULL,
  "Issuer" varchar(512) NOT NULL,
  "AllowedDomainPattern" varchar(255) NULL,
  "Active" boolean NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_RBAC_IdentityProviders" PRIMARY KEY ("ProviderID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Permissions" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(200) NOT NULL,
  "ObjID" integer NOT NULL,
  "OperationID" integer NOT NULL,
  CONSTRAINT "PK_RBAC_Permissions" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Role_Permissions" (
  "RoleID" integer NOT NULL,
  "PermissionID" integer NOT NULL,
  CONSTRAINT "PK_RBAC_Role_Permissions" PRIMARY KEY ("RoleID", "PermissionID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Roles" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(200) NOT NULL,
  "BypassScope" boolean NOT NULL,
  CONSTRAINT "PK_RBAC_Roles" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."ScopeIdentityProviders" (
  "ScopeID" integer NOT NULL,
  "ProviderID" integer NOT NULL,
  "Active" boolean NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_RBAC_ScopeIdentityProviders" PRIMARY KEY ("ScopeID", "ProviderID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Scopes" (
  "ScopeID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ScopeType" varchar(32) NOT NULL,
  "Name" varchar(200) NOT NULL,
  "InstitutionID" integer NULL,
  "LabID" integer NULL,
  "OwnerUserID" integer NULL,
  "Active" boolean NOT NULL,
  "CreatedAtUtc" timestamptz NOT NULL,
  CONSTRAINT "PK_RBAC_Scopes" PRIMARY KEY ("ScopeID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Session_Roles" (
  "SessionID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  CONSTRAINT "PK_RBAC_Session_Roles" PRIMARY KEY ("SessionID", "RoleID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Sessions" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Name" varchar(200) NULL,
  "UserID" integer NOT NULL,
  "Created" timestamptz NOT NULL,
  "ActiveScopeID" integer NULL,
  "AuthProviderID" integer NULL,
  "AuthSubjectSnapshot" varchar(512) NULL,
  "AuthenticatedAtUtc" timestamptz NULL,
  CONSTRAINT "PK_RBAC_Sessions" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."UserRoleGrants" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "UserID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  "GrantType" varchar(16) NOT NULL,
  "ScopeID" integer NULL,
  "Active" boolean NOT NULL,
  "GrantedAtUtc" timestamptz NOT NULL,
  "RevokedAtUtc" timestamptz NULL,
  "ApprovalID" bigint NULL,
  CONSTRAINT "PK_RBAC_UserRoleGrants" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "RBAC"."Users" (
  "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "FullName" varchar(200) NOT NULL,
  "email" varchar(50) NOT NULL,
  "Active" integer NOT NULL,
  "username" varchar(50) NULL,
  CONSTRAINT "PK_RBAC_Users" PRIMARY KEY ("ID")
);

