"""
QC Parser module for parsing Picard-style deduplication metrics.

This module provides functionality to parse Picard-style quality control
metrics from deduplication files generated by Parabricks or other aligners.
"""

from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
import re
import json


def parse_deduplication_metrics(file_path: Path) -> Dict[str, Any]:
    """
    Parse Picard-style deduplication metrics from a file.

    Args:
        file_path: Path to the deduplication metrics file

    Returns:
        Dictionary containing parsed metrics
    """
    with open(file_path, 'r') as f:
        content = f.read()

    # Split into sections
    sections = content.split('## ')

    metrics_data = {}

    for section in sections:
        section = section.strip()
        if not section:
            continue

        lines = section.split('\n')
        header = lines[0].strip()

        if header.startswith('METRICS CLASS'):
            # Parse metrics section
            metrics_data.update(_parse_metrics_section(lines))
        elif header.startswith('HISTOGRAM'):
            # Parse histogram section
            metrics_data.update(_parse_histogram_section(lines))

    return metrics_data


def _parse_metrics_section(lines: List[str]) -> Dict[str, Any]:
    """
    Parse the METRICS CLASS section.

    Args:
        lines: Lines from the metrics section

    Returns:
        Dictionary with parsed metrics
    """
    metrics = {}

    # Find the header line (starts with LIBRARY or other field names)
    header_idx = None
    for i, line in enumerate(lines):
        if not line.startswith('##') and line.strip() and '\t' in line:
            # Check if this looks like a header (contains tabs and no numbers)
            if not any(char.isdigit() for char in line):
                header_idx = i
                break

    if header_idx is None:
        return metrics

    # Parse header
    headers = lines[header_idx].strip().split('\t')

    # Parse data rows
    data_rows = []
    for line in lines[header_idx + 1:]:
        line = line.strip()
        if not line or line.startswith('##'):
            continue
        values = line.split('\t')
        if len(values) == len(headers):
            row_dict = dict(zip(headers, values))
            # Convert numeric values
            for key, value in row_dict.items():
                try:
                    # Try to convert to float, then int if it's a whole number
                    float_val = float(value)
                    if float_val.is_integer():
                        row_dict[key] = int(float_val)
                    else:
                        row_dict[key] = float_val
                except ValueError:
                    pass  # Keep as string
            data_rows.append(row_dict)

    if data_rows:
        metrics['duplication_metrics'] = data_rows

    return metrics


def _parse_histogram_section(lines: List[str]) -> Dict[str, Any]:
    """
    Parse the HISTOGRAM section.

    Args:
        lines: Lines from the histogram section

    Returns:
        Dictionary with parsed histogram data
    """
    histogram_data = {}

    # Find the BIN header
    bin_header_idx = None
    for i, line in enumerate(lines):
        if line.strip().startswith('BIN'):
            bin_header_idx = i
            break

    if bin_header_idx is None:
        return histogram_data

    # Parse histogram headers
    hist_headers = lines[bin_header_idx].strip().split('\t')

    # Parse histogram data
    hist_rows = []
    for line in lines[bin_header_idx + 1:]:
        line = line.strip()
        if not line or line.startswith('##'):
            continue
        values = line.split('\t')
        if len(values) == len(hist_headers):
            row_dict = {}
            for header, value in zip(hist_headers, values):
                try:
                    float_val = float(value)
                    if float_val.is_integer():
                        row_dict[header] = int(float_val)
                    else:
                        row_dict[header] = float_val
                except ValueError:
                    row_dict[header] = value
            hist_rows.append(row_dict)

    if hist_rows:
        histogram_data['duplication_histogram'] = hist_rows

    return histogram_data


def find_metrics_files(metrics_root: Path) -> List[Path]:
    """
    Find all deduplication metrics files in the metrics root directory.

    Args:
        metrics_root: Root directory containing metrics files

    Returns:
        List of paths to deduplication metrics files
    """
    metrics_files = []

    # Look for files ending with deduplicate_metrics.txt
    for pattern in ['*deduplicate_metrics.txt', '*duplication_metrics.txt']:
        metrics_files.extend(list(metrics_root.rglob(pattern)))

    return sorted(metrics_files)


def parse_all_metrics(metrics_root: Path) -> Dict[str, Any]:
    """
    Parse all metrics files in the metrics root directory.

    Args:
        metrics_root: Root directory containing metrics files

    Returns:
        Dictionary containing all parsed metrics organized by sample
    """
    metrics_files = find_metrics_files(metrics_root)
    all_metrics = {}

    for metrics_file in metrics_files:
        # Extract sample name from file path
        # Expected format: /path/to/sample_name/sample_name.deduplicate_metrics.txt
        sample_name = metrics_file.parent.name

        try:
            sample_metrics = parse_deduplication_metrics(metrics_file)
            if sample_metrics:
                all_metrics[sample_name] = sample_metrics
        except Exception as e:
            print(f"Warning: Failed to parse {metrics_file}: {e}")
            continue

    return all_metrics


def calculate_summary_stats(metrics_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Calculate summary statistics from parsed metrics.

    Args:
        metrics_data: Parsed metrics data

    Returns:
        Dictionary with summary statistics
    """
    summary = {}

    for sample_name, sample_data in metrics_data.items():
        if 'duplication_metrics' in sample_data:
            dup_metrics = sample_data['duplication_metrics']
            if dup_metrics:  # List of dicts
                metric = dup_metrics[0]  # Usually just one row

                summary[sample_name] = {
                    'total_reads': metric.get('UNPAIRED_READS_EXAMINED', 0) + metric.get('READ_PAIRS_EXAMINED', 0),
                    'duplication_rate': metric.get('PERCENT_DUPLICATION', 0.0),
                    'estimated_library_size': metric.get('ESTIMATED_LIBRARY_SIZE', 0),
                    'duplicate_reads': metric.get('READ_PAIR_DUPLICATES', 0),
                    'optical_duplicates': metric.get('READ_PAIR_OPTICAL_DUPLICATES', 0)
                }

    return summary