#!/usr/bin/env python3
"""
Generate PostgreSQL DDL twins (quoted PascalCase identifiers) for the legacy
EpiPortal schemas extracted into sql_mssql/*_schema.sql.

Also hardens cfg.study_group_member → portal."Samples" / portal."LabSamples"
and portal."Samples".analyte_id → cfg.analyte once clinical tables exist.

Usage:
  source .venv/bin/activate
  # Preferred: script from live Azure SQL (accurate types + extras)
  python scripts/generate_pg_clinical_ddl.py --from-live
  # Fallback: translate extracted MSSQL schema files
  python scripts/generate_pg_clinical_ddl.py --from-mssql-files
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

REPO = Path(__file__).resolve().parents[1]
PG_DIR = REPO / "workflow_engine" / "sql_pg"
MSSQL_DIR = REPO / "workflow_engine" / "sql_mssql"

SCHEMAS = ("Meta", "RBAC", "portal", "Contract", "Onboarding", "e_portal")
PORTAL_SKIP = {"resource_profile", "sample_field_contract"}


def _pg_type(type_name: str, max_length: int, precision: int, scale: int) -> str:
    t = type_name.lower()
    if t in ("nvarchar", "varchar", "nchar", "char", "sysname"):
        if max_length == -1:
            return "text"
        n = max_length // 2 if t.startswith("n") or t == "sysname" else max_length
        if n <= 0:
            return "text"
        return f"varchar({n})"
    if t in ("varbinary", "binary", "image"):
        return "bytea"
    if t in ("decimal", "numeric"):
        return f"numeric({precision},{scale})"
    if t in ("float", "real"):
        return "double precision" if t == "float" else "real"
    if t in ("money", "smallmoney"):
        return "numeric(19,4)"
    if t == "bit":
        return "boolean"
    if t in ("datetime", "datetime2", "smalldatetime"):
        return "timestamptz"
    if t == "date":
        return "date"
    if t == "time":
        return "time"
    if t == "uniqueidentifier":
        return "uuid"
    if t == "xml":
        return "xml"
    if t in ("json",):
        return "jsonb"
    if t in ("int", "integer"):
        return "integer"
    if t == "bigint":
        return "bigint"
    if t in ("smallint", "tinyint"):
        return "smallint" if t == "smallint" else "smallint"
    if t == "text" or t == "ntext":
        return "text"
    return "text"


def script_from_live() -> Dict[str, str]:
    import pyodbc

    drivers = [d for d in pyodbc.drivers() if "ODBC Driver" in d and "SQL Server" in d]
    driver = drivers[-1]
    cn = pyodbc.connect(
        f"DRIVER={{{driver}}};SERVER={os.environ['AZURE_SQL_SERVER']};"
        f"DATABASE={os.environ.get('AZURE_SQL_DB','MethylPipeline')};"
        f"UID={os.environ['AZURE_SQL_USER']};PWD={os.environ['AZURE_SQL_PASSWORD']};"
        f"Encrypt=yes;TrustServerCertificate=yes;"
    )
    out: Dict[str, str] = {}
    try:
        cur = cn.cursor()
        for schema in SCHEMAS:
            parts = [
                f'CREATE SCHEMA IF NOT EXISTS "{schema}";',
                "",
            ]
            # Also create lowercase alias schema for portal when needed? Plan says
            # quoted PascalCase + lowercase synonyms where MethylPipeline SQL uses them.
            if schema == "portal":
                parts.append("-- Lowercase synonym schema not created; use quoted portal.\"Samples\".")
                parts.append("")
            cur.execute(
                """
                SELECT t.name
                FROM sys.tables t
                JOIN sys.schemas s ON s.schema_id = t.schema_id
                WHERE s.name = ?
                ORDER BY t.name
                """,
                schema,
            )
            tables = [r[0] for r in cur.fetchall()]
            for table in tables:
                if schema == "portal" and table in PORTAL_SKIP:
                    continue
                cur.execute(
                    """
                    SELECT c.name, ty.name, c.max_length, c.precision, c.scale,
                           c.is_nullable, c.is_identity
                    FROM sys.columns c
                    JOIN sys.types ty ON ty.user_type_id = c.user_type_id
                    WHERE c.object_id = OBJECT_ID(?)
                    ORDER BY c.column_id
                    """,
                    f"{schema}.{table}",
                )
                cols = cur.fetchall()
                col_sql = []
                for cname, type_name, max_length, precision, scale, is_nullable, is_identity in cols:
                    pg_t = _pg_type(type_name, max_length, precision, scale)
                    if is_identity:
                        if pg_t in ("integer", "int"):
                            pg_t = "integer GENERATED BY DEFAULT AS IDENTITY"
                        elif pg_t == "bigint":
                            pg_t = "bigint GENERATED BY DEFAULT AS IDENTITY"
                        elif pg_t == "smallint":
                            pg_t = "smallint GENERATED BY DEFAULT AS IDENTITY"
                        else:
                            pg_t = f"{pg_t} GENERATED BY DEFAULT AS IDENTITY"
                    null = "" if not is_nullable else " NULL"
                    if not is_nullable and "GENERATED" not in pg_t:
                        null = " NOT NULL"
                    elif not is_nullable and "GENERATED" in pg_t:
                        null = " NOT NULL"
                    col_sql.append(f'  "{cname}" {pg_t}{null}')
                cur.execute(
                    """
                    SELECT c.name
                    FROM sys.indexes i
                    JOIN sys.index_columns ic
                      ON ic.object_id = i.object_id AND ic.index_id = i.index_id
                    JOIN sys.columns c
                      ON c.object_id = ic.object_id AND c.column_id = ic.column_id
                    WHERE i.object_id = OBJECT_ID(?) AND i.is_primary_key = 1
                    ORDER BY ic.key_ordinal
                    """,
                    f"{schema}.{table}",
                )
                pk = [r[0] for r in cur.fetchall()]
                pk_sql = ""
                if pk:
                    pk_list = ", ".join(f'"{c}"' for c in pk)
                    pk_sql = f',\n  CONSTRAINT "PK_{schema}_{table}" PRIMARY KEY ({pk_list})'
                parts.append(
                    f'CREATE TABLE IF NOT EXISTS "{schema}"."{table}" (\n'
                    + ",\n".join(col_sql)
                    + pk_sql
                    + "\n);"
                )
                parts.append("")
            # Cross-schema / intra FKs (add after all tables in this schema pass —
            # full FK graph applied in a second pass file).
            out[schema] = "\n".join(parts)
        # Second pass: FKs for all controlled schemas
        fk_parts = ["-- Cross-table foreign keys (idempotent)", ""]
        for schema in SCHEMAS:
            cur.execute(
                """
                SELECT fk.name,
                       SCHEMA_NAME(pt.schema_id), pt.name,
                       SCHEMA_NAME(rt.schema_id), rt.name
                FROM sys.foreign_keys fk
                JOIN sys.tables pt ON pt.object_id = fk.parent_object_id
                JOIN sys.tables rt ON rt.object_id = fk.referenced_object_id
                WHERE SCHEMA_NAME(pt.schema_id) = ?
                ORDER BY fk.name
                """,
                schema,
            )
            for fk_name, p_schema, p_table, r_schema, r_table in cur.fetchall():
                if p_schema == "portal" and p_table in PORTAL_SKIP:
                    continue
                cur.execute(
                    """
                    SELECT pc.name, rc.name
                    FROM sys.foreign_key_columns fkc
                    JOIN sys.columns pc
                      ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
                    JOIN sys.columns rc
                      ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
                    WHERE fkc.constraint_object_id = OBJECT_ID(?)
                    ORDER BY fkc.constraint_column_id
                    """,
                    f"{p_schema}.{fk_name}" if False else None,
                )
                # OBJECT_ID on FK name alone may fail; use sys.foreign_keys id
            cur.execute(
                """
                SELECT fk.object_id, fk.name,
                       SCHEMA_NAME(pt.schema_id), pt.name,
                       SCHEMA_NAME(rt.schema_id), rt.name
                FROM sys.foreign_keys fk
                JOIN sys.tables pt ON pt.object_id = fk.parent_object_id
                JOIN sys.tables rt ON rt.object_id = fk.referenced_object_id
                WHERE SCHEMA_NAME(pt.schema_id) = ?
                ORDER BY fk.name
                """,
                schema,
            )
            rows = cur.fetchall()
            for fk_oid, fk_name, p_schema, p_table, r_schema, r_table in rows:
                if p_schema == "portal" and p_table in PORTAL_SKIP:
                    continue
                cur.execute(
                    """
                    SELECT pc.name, rc.name
                    FROM sys.foreign_key_columns fkc
                    JOIN sys.columns pc
                      ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
                    JOIN sys.columns rc
                      ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
                    WHERE fkc.constraint_object_id = ?
                    ORDER BY fkc.constraint_column_id
                    """,
                    fk_oid,
                )
                cols = cur.fetchall()
                if not cols:
                    continue
                pcols = ", ".join(f'"{c[0]}"' for c in cols)
                rcols = ", ".join(f'"{c[1]}"' for c in cols)
                fk_parts.append(
                    f'DO $fk$\n'
                    f'BEGIN\n'
                    f'  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'{fk_name}\') THEN\n'
                    f'    ALTER TABLE "{p_schema}"."{p_table}"\n'
                    f'      ADD CONSTRAINT "{fk_name}"\n'
                    f'      FOREIGN KEY ({pcols}) REFERENCES "{r_schema}"."{r_table}" ({rcols});\n'
                    f'  END IF;\n'
                    f'  EXCEPTION WHEN others THEN\n'
                    f'    RAISE NOTICE \'skip FK {fk_name}: %\', SQLERRM;\n'
                    f'END $fk$;\n'
                )
        out["_fks"] = "\n".join(fk_parts)
    finally:
        cn.close()
    return out


CFG_HARDENING = r'''
-- Harden cfg ↔ portal clinical FKs once portal."Samples" / "LabSamples" exist.
DO $cfg$
BEGIN
  IF to_regclass('portal."Samples"') IS NOT NULL THEN
    -- analyte_id column on Samples (parity with Azure SQL)
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'portal' AND table_name = 'Samples' AND column_name = 'analyte_id'
    ) THEN
      ALTER TABLE portal."Samples" ADD COLUMN analyte_id bigint NULL;
    END IF;
    IF to_regclass('cfg.analyte') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_portal_Samples_analyte') THEN
      ALTER TABLE portal."Samples"
        ADD CONSTRAINT "FK_portal_Samples_analyte"
        FOREIGN KEY (analyte_id) REFERENCES cfg.analyte(id);
    END IF;
  END IF;

  IF to_regclass('cfg.study_group_member') IS NOT NULL
     AND to_regclass('portal."Samples"') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_cfg_sgm_portal_sample') THEN
    ALTER TABLE cfg.study_group_member
      ADD CONSTRAINT "FK_cfg_sgm_portal_sample"
      FOREIGN KEY (portal_sample_id) REFERENCES portal."Samples"("ID");
  END IF;

  IF to_regclass('cfg.study_group_member') IS NOT NULL
     AND to_regclass('portal."LabSamples"') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_cfg_sgm_lab_sample') THEN
    ALTER TABLE cfg.study_group_member
      ADD CONSTRAINT "FK_cfg_sgm_lab_sample"
      FOREIGN KEY (lab_sample_id) REFERENCES portal."LabSamples"("ID");
  END IF;
END $cfg$;

-- Lowercase views so existing PG SQL that probes portal.samples still works.
DO $views$
BEGIN
  IF to_regclass('portal."Samples"') IS NOT NULL THEN
    EXECUTE 'CREATE OR REPLACE VIEW portal.samples AS SELECT * FROM portal."Samples"';
  END IF;
  IF to_regclass('portal."LabSamples"') IS NOT NULL THEN
    EXECUTE 'CREATE OR REPLACE VIEW portal.labsamples AS SELECT * FROM portal."LabSamples"';
  END IF;
END $views$;
'''


def write_pg_files(parts: Dict[str, str]) -> None:
    mapping = {
        "Meta": "meta_schema.sql",
        "RBAC": "rbac_schema.sql",
        "portal": "portal_clinical_schema.sql",
        "Contract": "contract_schema.sql",
        "Onboarding": "onboarding_schema.sql",
        "e_portal": "e_portal_schema.sql",
    }
    header = (
        "-- Auto-generated by scripts/generate_pg_clinical_ddl.py\n"
        "-- Quoted PascalCase identifiers match Azure SQL for EpiPortal cutover.\n"
        "-- Lowercase views portal.samples / portal.labsamples provided in cfg hardening.\n\n"
    )
    for schema, filename in mapping.items():
        body = header + parts[schema] + "\n"
        (PG_DIR / filename).write_text(body, encoding="utf-8")
        print(f"Wrote sql_pg/{filename}")
    fk_file = PG_DIR / "legacy_cross_schema_fks.sql"
    fk_file.write_text(header + parts.get("_fks", "") + "\n" + CFG_HARDENING + "\n", encoding="utf-8")
    print(f"Wrote sql_pg/{fk_file.name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--from-live", action="store_true")
    parser.add_argument("--from-mssql-files", action="store_true")
    args = parser.parse_args()
    if not args.from_live and not args.from_mssql_files:
        args.from_live = True
    if args.from_live:
        parts = script_from_live()
        write_pg_files(parts)
        return 0
    print("--from-mssql-files not implemented; use --from-live", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
