#!/bin/bash
# Extract a MethylExtractor pipeline tarball and configure PATH + HDF5_PLUGIN_PATH.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/install_methyl_extractor_tarball.sh [options]

Options:
  --tarball PATH        Path to methyl-extractor-linux-<arch>.tar.gz (required)
  --dest DIR            Install root (default: /work/goliath/methyl-extractor-<arch>)
  --arch KEY            aarch64 or amd64 (default: detect from tarball name or machine)
  --goliath-root PATH GoliathOmics root for env file (default: /work/goliath)
  --user-env            Append source line to ~/.bashrc (default: yes)
  --no-user-env         Skip ~/.bashrc update
  -h, --help            Show this help

After install, open a new shell or run:
  source /work/goliath/env/methyl-extractor-<arch>.env

Production workers get the same variables from scripts/write_worker_env.sh during promote.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=detect_platform.sh
source "$SCRIPT_DIR/detect_platform.sh"

TARBALL=""
DEST=""
ARCH=""
GOLIATH_ROOT="${GOLIATH_ROOT:-/work/goliath}"
USER_ENV=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tarball) TARBALL="${2:-}"; shift 2 ;;
    --dest) DEST="${2:-}"; shift 2 ;;
    --arch) ARCH="${2:-}"; shift 2 ;;
    --goliath-root) GOLIATH_ROOT="${2:-}"; shift 2 ;;
    --user-env) USER_ENV=1; shift ;;
    --no-user-env) USER_ENV=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

info() { echo "[INFO] $*"; }
die() { echo "[ERROR] $*" >&2; exit 1; }

[[ -n "$TARBALL" ]] || die "--tarball is required"
[[ -f "$TARBALL" ]] || die "Tarball not found: $TARBALL"

basename_tar="$(basename "$TARBALL")"
if [[ -z "$ARCH" ]]; then
  if [[ "$basename_tar" =~ methyl-extractor-linux-(aarch64|amd64) ]]; then
    ARCH="${BASH_REMATCH[1]}"
  else
    ARCH="$(platform_arch_key "$(detect_uname_arch)")"
  fi
fi

DEST="${DEST:-$GOLIATH_ROOT/methyl-extractor-${ARCH}}"
ENV_FILE="$GOLIATH_ROOT/env/methyl-extractor-${ARCH}.env"
MARKER="# GoliathOmics MethylExtractor environment ($ARCH)"

info "Installing to $DEST"
if [[ -e "$DEST" && ! -w "$DEST" ]]; then
  SUDO="sudo"
else
  SUDO=""
fi
$SUDO mkdir -p "$DEST"
if [[ -d "$DEST/bin" ]]; then
  info "Removing previous install under $DEST"
  $SUDO rm -rf "$DEST/bin" "$DEST/lib" "$DEST/VERSION.txt" "$DEST/env.sh" 2>/dev/null || true
fi
$SUDO tar -xzf "$TARBALL" -C "$DEST"
$SUDO chown -R "$(id -un)":"$(id -gn)" "$DEST" 2>/dev/null || true
[[ -x "$DEST/bin/MethylExtractor" ]] || die "Expected $DEST/bin/MethylExtractor after extract"

# env.sh inside tarball (if present) for manual: source <dest>/env.sh
cat >"$DEST/env.sh" <<EOF
# Source this file: source "$DEST/env.sh"
export METHYL_EXTRACTOR_BIN="$DEST/bin/MethylExtractor"
export HDF5_PLUGIN_PATH="$DEST/lib/hdf5_zstd_plugin"
export PATH="$DEST/bin:\$PATH"
EOF
chmod +x "$DEST/env.sh" 2>/dev/null || true

mkdir -p "$GOLIATH_ROOT/env"
cat >"$ENV_FILE" <<EOF
# Generated by install_methyl_extractor_tarball.sh — do not edit by hand.
export METHYL_EXTRACTOR_BIN="$DEST/bin/MethylExtractor"
export HDF5_PLUGIN_PATH="$DEST/lib/hdf5_zstd_plugin"
export PATH="$DEST/bin:\$PATH"
EOF
info "Wrote $ENV_FILE"

if [[ "$USER_ENV" -eq 1 ]]; then
  bashrc="${HOME}/.bashrc"
  if [[ -f "$bashrc" ]] && ! grep -qF "$MARKER" "$bashrc" 2>/dev/null; then
    {
      echo ""
      echo "$MARKER"
      echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
    } >>"$bashrc"
    info "Appended source line to $bashrc"
  fi
fi

info "MethylExtractor: $DEST/bin/MethylExtractor"
info "HDF5_PLUGIN_PATH=$DEST/lib/hdf5_zstd_plugin"
"$DEST/bin/MethylExtractor" --help >/dev/null
info "Install OK. Run: source \"$ENV_FILE\""
