#!/bin/bash
# Provision a gateway VM (local disk only — does not use /work).
# Database schema/catalog must already be applied on a privileged host.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/provision_gateway_node.sh [options]

Installs methyl-gateway on this VM's local disk. Does not mount or write /work.
Workers keep genomes/samples/releases on the shared /work tree.

Options:
  --root PATH              Gateway local root (default: /opt/methyl-gateway)
  --release-dir PATH       Optional wheels dir; installs a local venv from it
  --arch KEY               aarch64 or amd64 (default: detect)
  --hostname NAME          TLS server_name for nginx (default: hostname -f)
  --skip-nginx             Do not install/configure nginx
  --skip-health            Do not curl /v1/health
  --no-start               Pass --no-start to systemd installers
  --dry-run
  -h, --help

Env: GATEWAY_HOSTNAME, GATEWAY_CERT_DIR (/etc/ssl/methyl-gateway).
     Copy deploy/env/gateway.mssql.env.example + gateway.security.env.example
     into <root>/env/gateway.env before or during this script (existing file kept).
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=detect_platform.sh
source "$SCRIPT_DIR/detect_platform.sh"

ROOT="${GOLIATH_ROOT:-/opt/methyl-gateway}"
RELEASE_DIR=""
ARCH=""
HOSTNAME_ARG="${GATEWAY_HOSTNAME:-}"
SKIP_NGINX=0
SKIP_HEALTH=0
NO_START=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --release-dir) RELEASE_DIR="${2:-}"; shift 2 ;;
    --arch) ARCH="${2:-}"; shift 2 ;;
    --hostname) HOSTNAME_ARG="${2:-}"; shift 2 ;;
    --skip-nginx) SKIP_NGINX=1; shift ;;
    --skip-health) SKIP_HEALTH=1; shift ;;
    --no-start) NO_START=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] $*"
  else
    "$@"
  fi
}

die() { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "[INFO] $*"; }

ARCH="${ARCH:-$(platform_arch_key "$(detect_uname_arch)")}"
HOSTNAME_ARG="${HOSTNAME_ARG:-$(hostname -f 2>/dev/null || echo gateway.local)}"
if [[ "$ROOT" == /work || "$ROOT" == /work/* ]]; then
  die "Gateway --root must be this VM's local disk, not the worker /work share (got $ROOT)"
fi
ENV_DIR="$ROOT/env"
VENV=""
if [[ -x "$ROOT/venv-${ARCH}/bin/python" ]]; then
  VENV="$ROOT/venv-${ARCH}"
elif [[ -x "$ROOT/venv/bin/python" ]]; then
  VENV="$ROOT/venv"
else
  VENV="$ROOT/venv-${ARCH}"
fi

info "Gateway provision (no /work)"
info "  root: $ROOT"
info "  venv: $VENV"

run mkdir -p "$ENV_DIR" "$ROOT"

if [[ -n "$RELEASE_DIR" ]]; then
  info "Installing release wheels into $VENV ..."
  run bash "$SCRIPT_DIR/install_release.sh" --release-dir "$RELEASE_DIR" --venv "$VENV"
fi

if [[ ! -f "$ENV_DIR/gateway.env" ]]; then
  info "Writing $ENV_DIR/gateway.env from templates (edit secrets / MI before production use)"
  {
    echo "# Generated by provision_gateway_node.sh — edit in place; do not commit."
    if [[ -f "$REPO_ROOT/deploy/env/gateway.mssql.env.example" ]]; then
      cat "$REPO_ROOT/deploy/env/gateway.mssql.env.example"
    elif [[ -f "$SCRIPT_DIR/../deploy/env/gateway.mssql.env.example" ]]; then
      cat "$SCRIPT_DIR/../deploy/env/gateway.mssql.env.example"
    fi
    echo ""
    if [[ -f "$REPO_ROOT/deploy/env/gateway.security.env.example" ]]; then
      cat "$REPO_ROOT/deploy/env/gateway.security.env.example"
    fi
  } | run tee "$ENV_DIR/gateway.env" >/dev/null
fi

GW_ARGS=(--root "$ROOT" --arch "$ARCH")
[[ "$NO_START" -eq 1 ]] && GW_ARGS+=(--no-start)
info "Installing methyl-gateway systemd ..."
if [[ "$(id -u)" -eq 0 ]]; then
  run bash "$SCRIPT_DIR/install_gateway_systemd.sh" "${GW_ARGS[@]}"
else
  run sudo bash "$SCRIPT_DIR/install_gateway_systemd.sh" "${GW_ARGS[@]}"
fi

if [[ "$SKIP_NGINX" -eq 0 ]]; then
  info "Configuring nginx TLS ..."
  NGINX_ARGS=(--hostname "$HOSTNAME_ARG")
  if [[ "$(id -u)" -eq 0 ]]; then
    run bash "$SCRIPT_DIR/setup_gateway_nginx.sh" "${NGINX_ARGS[@]}"
  else
    run sudo bash "$SCRIPT_DIR/setup_gateway_nginx.sh" "${NGINX_ARGS[@]}"
  fi
fi

if [[ "$SKIP_HEALTH" -eq 0 && "$DRY_RUN" -eq 0 && "$NO_START" -eq 0 ]]; then
  if curl -fsS -o /dev/null "http://127.0.0.1:8080/v1/health"; then
    info "OK: http://127.0.0.1:8080/v1/health"
  else
    die "Gateway health check failed at http://127.0.0.1:8080/v1/health"
  fi
fi

info "Gateway provision complete. Workers set WORKER_API_BASE=https://${HOSTNAME_ARG}/v1"
