#!/bin/bash
# Install Docker Engine and NVIDIA Container Toolkit on Ubuntu GPU worker nodes.
# Optionally pull the Clara Parabricks image and write parabricks.env.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/setup_gpu_node.sh [options]

Options:
  --pull-parabricks   Pull METHYL_PARABRICKS_IMAGE after setup
  --env-dir PATH      Write parabricks.env (default: /work/epimethyl/env)
  --skip-docker       Skip Docker / NVIDIA toolkit install (verify only)
  -h, --help          Show this help

Prerequisites:
  - Ubuntu/Debian with apt-get
  - NVIDIA driver (nvidia-smi must work)
  - sudo for package installation

Environment:
  METHYL_PARABRICKS_IMAGE   Override Parabricks image (else platform_matrix.env)
  PLATFORM_MATRIX_FILE      Path to scripts/platform_matrix.env
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=detect_platform.sh
source "$SCRIPT_DIR/detect_platform.sh"

PULL_PARABRICKS=0
SKIP_DOCKER=0
ENV_DIR="${EPIMETHYL_ENV_DIR:-/work/epimethyl/env}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pull-parabricks) PULL_PARABRICKS=1; shift ;;
    --env-dir) ENV_DIR="${2:-}"; shift 2 ;;
    --skip-docker) SKIP_DOCKER=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

info() { echo "[INFO] $*"; }
warn() { echo "[WARN] $*"; }
die() { echo "[ERROR] $*" >&2; exit 1; }

if ! command -v nvidia-smi >/dev/null 2>&1; then
  die "nvidia-smi not found. Install NVIDIA drivers before GPU node setup."
fi
info "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo unknown)"

sudo_cmd=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "sudo required for package installation"
  sudo_cmd="sudo"
fi

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    info "docker already installed: $(docker --version)"
    return 0
  fi
  info "Installing Docker Engine..."
  $sudo_cmd apt-get update
  $sudo_cmd apt-get install -y ca-certificates curl gnupg
  $sudo_cmd install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | $sudo_cmd gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    $sudo_cmd chmod a+r /etc/apt/keyrings/docker.gpg
  fi
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${VERSION_CODENAME:-jammy}") stable" | \
    $sudo_cmd tee /etc/apt/sources.list.d/docker.list >/dev/null
  $sudo_cmd apt-get update
  $sudo_cmd apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  $sudo_cmd systemctl enable --now docker || true
  if [[ "$(id -u)" -ne 0 ]] && ! groups | grep -q docker; then
    warn "Add user to docker group: sudo usermod -aG docker $USER && newgrp docker"
  fi
}

install_nvidia_container_toolkit() {
  if command -v nvidia-ctk >/dev/null 2>&1; then
    info "nvidia-ctk already installed"
  else
    info "Installing NVIDIA Container Toolkit..."
    $sudo_cmd apt-get update
    $sudo_cmd apt-get install -y curl gnupg
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
      $sudo_cmd gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      $sudo_cmd tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    $sudo_cmd apt-get update
    $sudo_cmd apt-get install -y nvidia-container-toolkit
  fi
  info "Configuring Docker runtime for NVIDIA..."
  $sudo_cmd nvidia-ctk runtime configure --runtime=docker
  $sudo_cmd systemctl restart docker || $sudo_cmd service docker restart || true
}

if [[ "$SKIP_DOCKER" -eq 0 ]]; then
  install_docker
  install_nvidia_container_toolkit
else
  info "Skipping Docker install (--skip-docker)"
fi

IMAGE="${METHYL_PARABRICKS_IMAGE:-$(resolve_parabricks_image)}"
if [[ -z "$IMAGE" ]]; then
  warn "METHYL_PARABRICKS_IMAGE not set and platform matrix has no default"
else
  export METHYL_PARABRICKS_IMAGE="$IMAGE"
  info "Parabricks image: $METHYL_PARABRICKS_IMAGE"
  mkdir -p "$ENV_DIR"
  cat >"$ENV_DIR/parabricks.env" <<EOF
# Generated by scripts/setup_gpu_node.sh
METHYL_PARABRICKS_IMAGE=$METHYL_PARABRICKS_IMAGE
METHYL_PARABRICKS_GPU_FLAGS=--gpus all
EOF
  info "Wrote $ENV_DIR/parabricks.env"
fi

if [[ "$PULL_PARABRICKS" -eq 1 ]]; then
  [[ -n "$IMAGE" ]] || die "Cannot pull Parabricks: METHYL_PARABRICKS_IMAGE unset"
  info "Pulling $IMAGE ..."
  docker pull "$IMAGE"
fi

REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ -x "$REPO_ROOT/scripts/verify_parabricks.sh" && -n "${IMAGE:-}" ]]; then
  info "Running verify_parabricks.sh ..."
  export METHYL_PARABRICKS_IMAGE="$IMAGE"
  bash "$REPO_ROOT/scripts/verify_parabricks.sh" || warn "Parabricks verification failed (image may need NGC login)"
fi

info "GPU node setup complete."
