#!/bin/bash
# Write worker.env and parabricks.env from a release manifest.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/write_worker_env.sh [options]

Options:
  --root PATH          Epimethyl root (default: /work/epimethyl)
  --manifest PATH      manifest.json (default: <root>/current/manifest.json)
  --arch KEY           aarch64 or amd64 (default: detect from uname)
  --worker-api-base URL  WORKER_API_BASE (default: env or http://localhost:8080/v1)
  -h, --help           Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=detect_platform.sh
source "$SCRIPT_DIR/detect_platform.sh"

ROOT="${EPIMETHYL_ROOT:-/work/epimethyl}"
MANIFEST=""
ARCH=""
WORKER_API_BASE="${WORKER_API_BASE:-https://gateway.example.com/v1}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --manifest) MANIFEST="${2:-}"; shift 2 ;;
    --arch) ARCH="${2:-}"; shift 2 ;;
    --worker-api-base) WORKER_API_BASE="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

die() { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "[INFO] $*"; }

ARCH="${ARCH:-$(platform_arch_key "$(detect_uname_arch)")}"
MANIFEST="${MANIFEST:-$ROOT/current/manifest.json}"
[[ -f "$MANIFEST" ]] || die "Manifest not found: $MANIFEST"

read_manifest() {
  python3 - "$MANIFEST" "$ARCH" <<'PY'
import json, sys
path, arch = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    m = json.load(f)
art = (m.get("artifacts") or {}).get(arch) or {}
print(m.get("parabricks_image", ""))
print(m.get("docker_data_root", f"/work/epimethyl/docker"))
print(m.get("version", ""))
PY
}

mapfile -t _lines < <(read_manifest)
PARABRICKS_IMAGE="${_lines[0]:-$(resolve_parabricks_image)}"
DOCKER_DATA_ROOT="${_lines[1]:-/work/epimethyl/docker}"
RELEASE_VERSION="${_lines[2]:-unknown}"

VENV_DIR="$ROOT/venv-${ARCH}"
ME_ROOT="$ROOT/methyl-extractor-${ARCH}"
ME_BIN="$ME_ROOT/bin/MethylExtractor"
PLUGIN_DIR="$ME_ROOT/lib/hdf5_zstd_plugin"

if [[ ! -x "$ME_BIN" ]]; then
  ME_BIN="${METHYL_EXTRACTOR_BIN:-MethylExtractor}"
  PLUGIN_DIR="${HDF5_PLUGIN_PATH:-/usr/local/hdf5/lib/plugin}"
fi

ENV_DIR="$ROOT/env"
mkdir -p "$ENV_DIR"
WORKER_PATH="$(expand_worker_path "$VENV_DIR")"

cat >"$ENV_DIR/worker.env" <<EOF
# Generated by scripts/write_worker_env.sh (release ${RELEASE_VERSION})
# EnvironmentFile= does not expand variables — PATH must be literal.
EPIMETHYL_ROOT=$ROOT
EPIMETHYL_RELEASE=$RELEASE_VERSION
WORKER_API_BASE=$WORKER_API_BASE
DOCKER_DATA_ROOT=$DOCKER_DATA_ROOT
# WORKER_ID=
# WORKER_TOKEN=
# WORKER_CAPABILITY=
METHYL_EXTRACTOR_BIN=$ME_BIN
HDF5_PLUGIN_PATH=$PLUGIN_DIR
PATH=$WORKER_PATH
METHYL_PROFILE_DIR=$ROOT/current/runtime-bundle/domain/profiles
TMPDIR=/var/tmp/methyl-samtools
EOF

if [[ -n "$PARABRICKS_IMAGE" ]]; then
  echo "METHYL_PARABRICKS_IMAGE=$PARABRICKS_IMAGE" >>"$ENV_DIR/worker.env"
  # Quote: unquoted `--gpus all` breaks `set -a; source worker.env` (runs `all`).
  echo 'METHYL_PARABRICKS_GPU_FLAGS="--gpus all"' >>"$ENV_DIR/worker.env"
fi

# Sage DDA (CPU, proteomics.sage) — advertise on any worker (incl. non-GPU) when set.
SAGE_IMAGE="${METHYL_SAGE_IMAGE:-$(resolve_proteomics_image sage 2>/dev/null || true)}"
if [[ -n "$SAGE_IMAGE" ]]; then
  echo "METHYL_SAGE_IMAGE=$SAGE_IMAGE" >>"$ENV_DIR/worker.env"
fi

# methylGrapher WGBS image pull/load helper only — science knobs live in
# actionConfig.methylgrapher_wgbs → task resolvedConfig (not worker.env).
METHYLGRAPHER_IMAGE="${METHYL_METHYLGRAPHER_IMAGE:-$(resolve_methylgrapher_image 2>/dev/null || true)}"
if [[ -n "$METHYLGRAPHER_IMAGE" ]]; then
  echo "METHYL_METHYLGRAPHER_IMAGE=$METHYLGRAPHER_IMAGE" >>"$ENV_DIR/worker.env"
fi

# GPU HBM admission / post-action release (host flock; not science resolvedConfig).
# Prefer free-fraction of total HBM; absolute GiB is legacy-only.
HBM_FRAC="${METHYL_GPU_HBM_FREE_FRACTION:-0.90}"
HBM_WAIT="${METHYL_GPU_ALIGN_HBM_WAIT_S:-180}"
{
  echo "METHYL_GPU_HBM_FREE_FRACTION=$HBM_FRAC"
  echo "METHYL_GPU_ALIGN_HBM_WAIT_S=$HBM_WAIT"
} >>"$ENV_DIR/worker.env"

cat >"$ENV_DIR/parabricks.env" <<EOF
# Generated by scripts/write_worker_env.sh
METHYL_PARABRICKS_IMAGE=${PARABRICKS_IMAGE:-}
METHYL_PARABRICKS_GPU_FLAGS="--gpus all"
EOF

info "Wrote $ENV_DIR/worker.env"
info "Wrote $ENV_DIR/parabricks.env"
