#!/bin/bash
# Write worker.env and parabricks.env from a release manifest.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/write_worker_env.sh [options]

Options:
  --root PATH          Epimethyl root (default: /work/epimethyl)
  --manifest PATH      manifest.json (default: <root>/current/manifest.json)
  --arch KEY           aarch64 or amd64 (default: detect from uname)
  --worker-api-base URL  WORKER_API_BASE (default: env or http://localhost:8080/v1)
  -h, --help           Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=detect_platform.sh
source "$SCRIPT_DIR/detect_platform.sh"

ROOT="${EPIMETHYL_ROOT:-/work/epimethyl}"
MANIFEST=""
ARCH=""
WORKER_API_BASE="${WORKER_API_BASE:-http://localhost:8080/v1}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --manifest) MANIFEST="${2:-}"; shift 2 ;;
    --arch) ARCH="${2:-}"; shift 2 ;;
    --worker-api-base) WORKER_API_BASE="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

die() { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "[INFO] $*"; }

ARCH="${ARCH:-$(platform_arch_key "$(detect_uname_arch)")}"
MANIFEST="${MANIFEST:-$ROOT/current/manifest.json}"
[[ -f "$MANIFEST" ]] || die "Manifest not found: $MANIFEST"

read_manifest() {
  python3 - "$MANIFEST" "$ARCH" <<'PY'
import json, sys
path, arch = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    m = json.load(f)
art = (m.get("artifacts") or {}).get(arch) or {}
print(m.get("parabricks_image", ""))
print(m.get("docker_data_root", f"/work/epimethyl/docker"))
print(m.get("version", ""))
PY
}

mapfile -t _lines < <(read_manifest)
PARABRICKS_IMAGE="${_lines[0]:-$(resolve_parabricks_image)}"
DOCKER_DATA_ROOT="${_lines[1]:-/work/epimethyl/docker}"
RELEASE_VERSION="${_lines[2]:-unknown}"

VENV_DIR="$ROOT/venv-${ARCH}"
ME_ROOT="$ROOT/methyl-extractor-${ARCH}"
ME_BIN="$ME_ROOT/bin/MethylExtractor"
PLUGIN_DIR="$ME_ROOT/lib/hdf5_zstd_plugin"

if [[ ! -x "$ME_BIN" ]]; then
  ME_BIN="${METHYL_EXTRACTOR_BIN:-MethylExtractor}"
  PLUGIN_DIR="${HDF5_PLUGIN_PATH:-/usr/local/hdf5/lib/plugin}"
fi

ENV_DIR="$ROOT/env"
mkdir -p "$ENV_DIR"
WORKER_PATH="$(expand_worker_path "$VENV_DIR")"

cat >"$ENV_DIR/worker.env" <<EOF
# Generated by scripts/write_worker_env.sh (release ${RELEASE_VERSION})
# EnvironmentFile= does not expand variables — PATH must be literal.
EPIMETHYL_ROOT=$ROOT
EPIMETHYL_RELEASE=$RELEASE_VERSION
WORKER_API_BASE=$WORKER_API_BASE
DOCKER_DATA_ROOT=$DOCKER_DATA_ROOT
# WORKER_ID=
# WORKER_TOKEN=
# WORKER_CAPABILITY=
METHYL_EXTRACTOR_BIN=$ME_BIN
HDF5_PLUGIN_PATH=$PLUGIN_DIR
PATH=$WORKER_PATH
EOF

if [[ -n "$PARABRICKS_IMAGE" ]]; then
  echo "METHYL_PARABRICKS_IMAGE=$PARABRICKS_IMAGE" >>"$ENV_DIR/worker.env"
  echo "METHYL_PARABRICKS_GPU_FLAGS=--gpus all" >>"$ENV_DIR/worker.env"
fi

cat >"$ENV_DIR/parabricks.env" <<EOF
# Generated by scripts/write_worker_env.sh
METHYL_PARABRICKS_IMAGE=${PARABRICKS_IMAGE:-}
METHYL_PARABRICKS_GPU_FLAGS=--gpus all
EOF

info "Wrote $ENV_DIR/worker.env"
info "Wrote $ENV_DIR/parabricks.env"
