"""Minimal valid golden I/O payloads per catalog action (source for JSON fixtures)."""

from __future__ import annotations

from typing import Any, Dict

_GUARD = {"overall_pass": True, "screening": {"disposition": "PASS"}}
_SCREEN = {"disposition": "PASS", "trim_front1": 0, "trim_tail1": 0, "trim_front2": 0, "trim_tail2": 0}

_FILE_FASTQ = {"type": "file", "basePath": "/data/fastq", "prefix": "S1/"}
_FILE_DEST = {"type": "file", "basePath": "/data/archive", "prefix": "studies/demo/S1/"}

GOLDEN_INPUTS: Dict[str, Dict[str, Any]] = {
    "pipeline.centroid": {"tool": "MethylCentroid", "projectPath": "/work/p/project.json"},
    "pipeline.detector": {"tool": "MethylDetector", "projectPath": "/work/p/project.json", "chromosome": "21"},
    "pipeline.dmp_select": {
        "tool": "MethylDmpSelect",
        "projectPath": "/work/p/project.json",
        "chromosome": "21",
    },
    "pipeline.mapper": {"tool": "MethylMapper", "projectPath": "/work/p/project.json"},
    "pipeline.gene_select": {
        "tool": "MethylGeneSelect",
        "projectPath": "/work/p/project.json",
        "runDir": "/work/p/monte_carlo_runs/run_0001",
    },
    "pipeline.gene_feature_select": {
        "tool": "MethylGeneFeatureSelect",
        "mapperDir": "/work/p/mapper",
        "outputDir": "/work/p/gene_features",
    },
    "pipeline.enricher": {"tool": "MethylEnricher", "projectPath": "/work/p/project.json"},
    "pipeline.progression": {"tool": "MethylProgression", "projectPath": "/work/p/project.json"},
    "pipeline.classifier": {"tool": "MethylClassifier", "projectPath": "/work/p/project.json"},
    "pipeline.predictor": {"tool": "MethylPredictor", "projectPath": "/work/p/project.json"},
    "pipeline.derived_measures": {"tool": "MethylDerivedMeasures", "projectPath": "/work/p/project.json"},
    "pipeline.cell_deconvolution": {"tool": "MethylCellDeconv", "projectPath": "/work/p/project.json"},
    "pipeline.residualize_fit": {"tool": "MethylResidualizeFit", "projectPath": "/work/p/project.json"},
    "pipeline.methylation_confounder_scores": {
        "tool": "MethylConfounderScores",
        "projectPath": "/work/p/project.json",
    },
    "pipeline.info_measures": {"tool": "MethylInfoTheory", "projectPath": "/work/p/project.json"},
    "context.resolve_project": {"tool": "ContextResolveProject", "projectPath": "/work/p/project.json"},
    "sample.parabricks_giraffe": {
        "tool": "ParabricksGiraffe",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.demultiplex": {
        "tool": "SampleDemultiplex",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
    },
    "sample.docker_align": {
        "tool": "SampleDockerAlign",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.download_fastq": {
        "tool": "SampleDownloadFastq",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "fastqSource": _FILE_FASTQ,
    },
    "sample.parabricks_fq2bam": {
        "tool": "ParabricksFq2Bam",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.delete_fastqs": {
        "tool": "SampleDeleteFastqs",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
    },
    "sample.trim_fastq": {
        "tool": "SampleTrimFastq",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
    },
    "sample.methyl_qc": {"sampleId": "S1", "sampleDir": "/work/samples/S1", "projectPath": "/work/p/project.json"},
    "sample.fragmentomics": {"sampleId": "S1", "sampleDir": "/work/samples/S1", "projectPath": "/work/p/project.json"},
    "sample.methyl_extract": {
        "tool": "MethylExtract",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.methylgrapher_wgbs_align": {
        "tool": "MethylGrapherWgbsAlign",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.methylgrapher_wgbs_extract": {
        "tool": "MethylGrapherWgbsExtract",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.extraction_qc": {
        "tool": "MethylExtractionQc",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.archive_sample": {
        "tool": "SampleArchive",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "sampleDestination": _FILE_DEST,
    },
    "sample.delete_bam": {"tool": "SampleDeleteBam", "sampleId": "S1", "sampleDir": "/work/samples/S1"},
    "sample.qc_failed": {
        "tool": "SampleMarkFailed",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "reason": "alignment_qc_failed",
    },
    "sample.parabricks_rna_fq2bam": {
        "tool": "ParabricksRnaFq2Bam",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.kallisto": {
        "tool": "ParabricksKallisto",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.rna_qc": {
        "tool": "RnaAlignmentQc",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.register_expression": {
        "tool": "RnaRegisterExpression",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "pipeline.rna_de_select": {
        "tool": "RnaDeSelect",
        "projectPath": "/work/p/project.json",
        "comparison": "healthy_vs_disease",
        "outputDir": "/work/p/rna_de/healthy_vs_disease",
    },
    "sample.download_msdata": {
        "tool": "SampleDownloadMsdata",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "fastqSource": _FILE_FASTQ,
    },
    "sample.diann": {
        "tool": "ProteomicsDiann",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.sage": {
        "tool": "ProteomicsSage",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.ingest_panel": {
        "tool": "ProteomicsIngestPanel",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
        "panelPath": "/work/p/data/olink_npx.csv",
        "panelFormat": "npx",
    },
    "sample.dl_rescore": {
        "tool": "ProteomicsProsit",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.casanovo": {
        "tool": "ProteomicsCasanovo",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "sample.register_abundance": {
        "tool": "ProteomicsRegisterAbundance",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
        "source": "diann",
    },
    "sample.proteomics_qc": {
        "tool": "ProteomicsQc",
        "sampleId": "S1",
        "sampleDir": "/work/samples/S1",
        "projectPath": "/work/p/project.json",
    },
    "pipeline.protein_de_select": {
        "tool": "ProteinDeSelect",
        "projectPath": "/work/p/project.json",
        "comparison": "healthy_vs_disease",
        "outputDir": "/work/p/protein_de/healthy_vs_disease",
    },
    "validation.plan_iterations": {"projectPath": "/work/p/project.json", "featureIterations": 2},
    "validation.stability": {"projectPath": "/work/p/project.json", "monteCarloRunsRoot": "/work/p/monte_carlo_runs"},
    "validation.biomarker_filter": {"projectPath": "/work/p/project.json", "runDir": "/work/p/monte_carlo_runs/run_0001"},
    "validation.prepare_freeze_project": {
        "projectPath": "/work/p/project.json",
        "monteCarloRunsRoot": "/work/p/monte_carlo_runs",
    },
    "validation.finalize_freeze_model_bundle": {
        "projectPath": "/work/p/project.json",
        "monteCarloRunsRoot": "/work/p/monte_carlo_runs",
        "productionOutputDir": "/work/p/monte_carlo_runs/production",
    },
    "validation.stability_freeze_readiness": {"projectPath": "/work/p/project.json"},
    "validation.link_artifacts": {
        "sourceRunDir": "/work/p/monte_carlo_runs/run_0001",
        "targetRunDir": "/work/p/monte_carlo_runs/model_mc/shared/run_0001",
    },
    "validation.model_bundle": {"projectPath": "/work/p/project.json"},
    "validation.model_train": {"projectPath": "/work/p/project.json", "backend": "tabular_sklearn"},
    "validation.model_predict": {"projectPath": "/work/p/project.json", "backend": "tabular_sklearn"},
    "validation.select_best_model": {"projectPath": "/work/p/project.json", "monteCarloRunsRoot": "/work/p/monte_carlo_runs"},
    "validation.model_mc": {
        "projectPath": "/work/p/project.json",
        "monteCarloRunsRoot": "/work/p/monte_carlo_runs",
        "requireArtifactReuse": True,
    },
    "validation.post_model_validation": {
        "projectPath": "/work/p/project.json",
        "monteCarloRunsRoot": "/work/p/monte_carlo_runs",
    },
    "workflow.const_bool": {"tool": "WorkflowConstBool", "value": True},
    "workflow.const_int": {"tool": "WorkflowConstInt", "value": 42},
    "workflow.const_string": {"tool": "WorkflowConstString", "value": "ready"},
    "workflow.const_path": {"tool": "WorkflowConstPath", "value": "/work/p/project.json"},
    "workflow.json_path_bool": {
        "tool": "WorkflowJsonPathBool",
        "documentPath": "/work/p/readiness/readiness.json",
        "jsonPath": "$.ready",
    },
    "workflow.json_path_int": {
        "tool": "WorkflowJsonPathInt",
        "documentPath": "/work/p/readiness/readiness.json",
        "jsonPath": "$.n_iterations",
    },
    "workflow.json_path_string": {
        "tool": "WorkflowJsonPathString",
        "documentPath": "/work/p/readiness/readiness.json",
        "jsonPath": "$.status",
    },
    "workflow.fs_stat": {"tool": "WorkflowFsStat", "path": "/work/p/project.json"},
}

GOLDEN_OUTPUTS: Dict[str, Dict[str, Any]] = {
    "pipeline.centroid": {
        "status": "ok",
        "chromosome": "21",
        "context": "CG",
        "output_dir": "/work/p/centroids",
        "centroid_h5_path": "/work/p/centroids/21-CG.h5",
        "n_samples": 10,
    },
    "pipeline.detector": {
        "status": "ok",
        "chromosome": "21",
        "context": "CG",
        "n_statistical_dmps": 1000,
        "n_biological_dmps": 200,
    },
    "pipeline.dmp_select": {"status": "ok", "chromosome": "21", "n_dmps_classifier": 50},
    "pipeline.mapper": {"status": "ok", "chromosome": "21", "n_output_genes": 120},
    "pipeline.gene_select": {"status": "ok", "run_dir": "/work/p/mc/run_0001", "selected_k": 25},
    "pipeline.gene_feature_select": {"status": "ok", "n_features": 32, "output_csv": "/work/p/out.csv"},
    "pipeline.enricher": {"status": "ok", "all_complete": True, "n_comparisons": 1},
    "pipeline.progression": {"status": "ok", "n_comparisons": 3},
    "pipeline.classifier": {"status": "ok", "model_path": "/work/p/models/model.pkl"},
    "pipeline.predictor": {"status": "ok", "balanced_accuracy": 0.85},
    "pipeline.derived_measures": {
        "status": "ok",
        "output_dir": "/work/p/derived_measures",
        "output_csv": "/work/p/derived_measures/genome_measures.csv",
        "n_samples": 10,
        "n_columns": 40,
    },
    "pipeline.cell_deconvolution": {
        "status": "ok",
        "output_dir": "/work/p/cell_fractions",
        "output_csv": "/work/p/cell_fractions/cell_fractions.csv",
        "n_samples": 10,
        "n_columns": 10,
        "n_ok": 10,
    },
    "pipeline.residualize_fit": {
        "status": "ok",
        "output_dir": "/work/p/production/residualize",
        "n_files": 1,
        "n_train_samples": 20,
        "manifest_path": "/work/p/production/residualize/residualize_manifest.json",
    },
    "pipeline.methylation_confounder_scores": {
        "status": "ok",
        "output_dir": "/work/p/confounder_scores",
        "output_csv": "/work/p/confounder_scores/confounder_scores.csv",
        "n_samples": 10,
        "n_columns": 10,
    },
    "pipeline.info_measures": {
        "status": "ok",
        "output_dir": "/work/p/info_measures",
        "output_csv": "/work/p/info_measures/info_measures.csv",
        "n_samples": 10,
        "n_columns": 20,
        "n_jsd_windows": 5,
    },
    "context.resolve_project": {
        "status": "ok",
        "resolvedProject": {
            "$type": "ResolvedProject",
            "projectPath": "/work/p/project.json",
        },
    },
    "sample.parabricks_giraffe": {
        "status": "ok",
        "sampleId": "S1",
        "bamPath": "/work/samples/S1/S1.bam",
    },
    "sample.demultiplex": {
        "status": "ok",
        "sampleId": "S1",
        "fastqR1": "/work/samples/S1/S1_1.fastq.gz",
        "fastqR2": "/work/samples/S1/S1_2.fastq.gz",
        "n_reads_kept": 1000000,
        "barcode": "BC01",
    },
    "sample.docker_align": {
        "status": "ok",
        "sampleId": "S1",
        "bamPath": "/work/samples/S1/S1.bam",
    },
    "sample.download_fastq": {"status": "ok", "sampleId": "S1", "fastqFiles": ["S1_1.fastq.gz"], "n_files": 1},
    "sample.parabricks_fq2bam": {
        "status": "ok",
        "sampleId": "S1",
        "bamPath": "/work/samples/S1/S1.bam",
    },
    "sample.delete_fastqs": {"status": "ok", "sampleId": "S1", "deleted": True, "n_files_removed": 2},
    "sample.trim_fastq": {
        "status": "ok",
        "sampleId": "S1",
        "trimmedR1": "/work/samples/S1/S1_1.trimmed.fastq.gz",
        "trimmedR2": "/work/samples/S1/S1_2.trimmed.fastq.gz",
    },
    "sample.methyl_qc": {
        "status": "ok",
        "sampleId": "S1",
        "qcPath": "/work/qc/S1.json",
        "guardrails": _GUARD,
        "screening": _SCREEN,
    },
    "sample.fragmentomics": {"status": "ok", "sampleId": "S1", "outputDir": "/work/frag/S1"},
    "sample.methyl_extract": {"status": "ok", "sampleId": "S1", "h5Files": ["21-CG.h5"], "n_h5_files": 1},
    "sample.methylgrapher_wgbs_align": {
        "status": "ok",
        "sampleId": "S1",
        "bamPath": "/work/samples/S1/S1.bam",
        "gafPath": "/work/samples/S1/S1.alignment.gaf",
        "metricsJson": "/work/samples/S1/S1.alignment_metrics.json",
        "qcMetricsTar": "/work/samples/S1/S1.qc-metrics.tar",
        "dedupMetricsPath": "/work/samples/S1/S1.deduplicate_metrics.txt",
        "conversionReportPath": "/work/samples/S1/S1.conversion_report.txt",
    },
    "sample.methylgrapher_wgbs_extract": {
        "status": "ok",
        "sampleId": "S1",
        "h5Files": ["21-CG.h5"],
        "n_h5_files": 1,
    },
    "sample.extraction_qc": {
        "status": "ok",
        "sampleId": "S1",
        "qcPath": "/work/samples/S1/S1.extraction_qc.json",
        "guardrails": _GUARD,
        "extraction_pass": True,
    },
    "sample.archive_sample": {
        "status": "ok",
        "sampleId": "S1",
        "archiveMode": "full",
        "remotePrefix": "studies/demo/S1/",
        "sampleArchived": True,
    },
    "sample.delete_bam": {"status": "ok", "sampleId": "S1", "deleted": True, "n_files_removed": 1},
    "sample.qc_failed": {"sampleId": "S1", "status": "QC_FAILED", "reason": "alignment_qc_failed"},
    "sample.parabricks_rna_fq2bam": {
        "status": "ok",
        "sampleId": "S1",
        "bamPath": "/work/samples/S1/S1.rna.bam",
        "geneCountsPath": "/work/samples/S1/S1.gene_counts.tsv",
    },
    "sample.kallisto": {
        "status": "ok",
        "sampleId": "S1",
        "abundancePath": "/work/samples/S1/S1.kallisto/abundance.tsv",
    },
    "sample.rna_qc": {
        "status": "ok",
        "sampleId": "S1",
        "qcPath": "/work/samples/S1/S1.rna_qc.json",
        "guardrails": _GUARD,
        "rnaQcPass": True,
    },
    "sample.register_expression": {
        "status": "ok",
        "sampleId": "S1",
        "expressionH5": "/work/samples/S1/S1.expression.h5",
        "n_genes": 25000,
        "quantMode": "star",
    },
    "pipeline.rna_de_select": {
        "status": "ok",
        "comparison": "healthy_vs_disease",
        "control_label": "healthy",
        "disease_label": "disease",
        "n_control": 10,
        "n_disease": 10,
        "n_genes_selected": 200,
        "balanced_accuracy": 0.82,
        "gene_panel_csv": "/work/p/rna_de/healthy_vs_disease/rna_de_panel.csv",
        "feature_mode": "rna_expression",
    },
    "sample.download_msdata": {"status": "ok", "sampleId": "S1", "fastqFiles": ["S1.raw"], "n_files": 1},
    "sample.diann": {
        "status": "ok",
        "sampleId": "S1",
        "reportTsv": "/work/samples/S1/S1.diann/report.tsv",
    },
    "sample.sage": {
        "status": "ok",
        "sampleId": "S1",
        "reportTsv": "/work/samples/S1/S1.sage/results.sage.tsv",
        "lfqTsv": "/work/samples/S1/S1.sage/lfq.tsv",
    },
    "sample.ingest_panel": {
        "status": "ok",
        "sampleId": "S1",
        "abundanceH5": "/work/samples/S1/S1.abundance.h5",
        "n_proteins": 3000,
        "source": "panel:npx",
    },
    "sample.dl_rescore": {
        "status": "ok",
        "sampleId": "S1",
        "reportTsv": "/work/samples/S1/S1.prosit/report.rescored.tsv",
        "n_ids_before": 4000,
        "n_ids_after": 5200,
    },
    "sample.casanovo": {
        "status": "ok",
        "sampleId": "S1",
        "peptidesCsv": "/work/samples/S1/S1.casanovo.mztab",
        "n_peptides": 1200,
    },
    "sample.register_abundance": {
        "status": "ok",
        "sampleId": "S1",
        "abundanceH5": "/work/samples/S1/S1.abundance.h5",
        "n_proteins": 4200,
        "source": "diann",
    },
    "sample.proteomics_qc": {
        "status": "ok",
        "sampleId": "S1",
        "qcPath": "/work/samples/S1/S1.proteomics_qc.json",
        "guardrails": _GUARD,
        "proteomicsQcPass": True,
    },
    "pipeline.protein_de_select": {
        "status": "ok",
        "comparison": "healthy_vs_disease",
        "control_label": "healthy",
        "disease_label": "disease",
        "n_control": 10,
        "n_disease": 10,
        "n_proteins_selected": 200,
        "balanced_accuracy": 0.8,
        "protein_panel_csv": "/work/p/protein_de/healthy_vs_disease/protein_de_panel.csv",
        "feature_mode": "proteomics_abundance",
    },
    "validation.plan_iterations": {
        "status": "ok",
        "projectPath": "/work/p/project.json",
        "n_iterations": 2,
        "iterations": [
            {
                "$type": "StratifiedCohortDraw",
                "runId": "run_0001",
                "phase": "feature",
                "projectPath": "/work/p/monte_carlo_runs/run_0001/project.json",
                "run_id": "run_0001",
                "runDir": "/work/p/monte_carlo_runs/run_0001",
            }
        ],
    },
    "validation.stability": {
        "status": "ok",
        "outputDir": "/work/p/monte_carlo_runs/stability",
        "summary": {"n_iterations": 5, "n_stable_dmps": 100},
    },
    "validation.biomarker_filter": {
        "status": "ok",
        "n_genes": 50,
        "outputCsv": "/work/p/gene_stability/biomarker_gene_pool.csv",
        "biomarker_filter": {"enabled": True, "mode": "ppi"},
    },
    "validation.prepare_freeze_project": {
        "status": "ok",
        "productionOutputDir": "/work/p/monte_carlo_runs/production",
        "projectPath": "/work/p/project.json",
    },
    "validation.finalize_freeze_model_bundle": {
        "status": "ok",
        "projectPath": "/work/p/project.json",
        "modelBundleDir": "/work/p/monte_carlo_runs/production/model_bundle",
        "n_mapper_rows": 120,
        "n_genes": 50,
    },
    "validation.stability_freeze_readiness": {"status": "ok", "ready": True, "outputDir": "/work/p"},
    "validation.link_artifacts": {"status": "ok", "linked_files": ["centroids", "detections"]},
    "validation.model_bundle": {
        "status": "ok",
        "bundleDir": "/work/p/model_bundle",
        "bundleH5": "/work/p/model_bundle/model_feature_bundle.h5",
    },
    "validation.model_train": {
        "status": "ok",
        "model_path": "/work/p/models/tabular-model.joblib",
        "backend": "tabular_sklearn",
    },
    "validation.model_predict": {
        "status": "ok",
        "predictions_path": "/work/p/predictions.csv",
        "n_samples": 20,
    },
    "validation.select_best_model": {
        "status": "ok",
        "selectedBackend": "tabular_sklearn",
        "selectionMetric": "balanced_accuracy",
    },
    "validation.model_mc": {"status": "ok", "modelMcRoot": "/work/p/monte_carlo_runs/model_mc", "n_iterations": 3},
    "validation.post_model_validation": {
        "status": "ok",
        "outputDir": "/work/p/post_model_validation",
        "passed": True,
    },
    "workflow.const_bool": {"status": "ok", "value": True},
    "workflow.const_int": {"status": "ok", "value": 42},
    "workflow.const_string": {"status": "ok", "value": "ready"},
    "workflow.const_path": {"status": "ok", "value": "/work/p/project.json"},
    "workflow.json_path_bool": {"status": "ok", "value": True},
    "workflow.json_path_int": {"status": "ok", "value": 10},
    "workflow.json_path_string": {"status": "ok", "value": "ready"},
    "workflow.fs_stat": {
        "status": "ok",
        "exists": True,
        "size": 1024,
        "mtimeUtc": "2026-07-21T00:00:00Z",
        "value": True,
    },
}
