--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 2025.3.149.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 4/29/2026 10:41:00 AM
-- Server version: 17.00.4035
--

--
-- Create schema [wf]
--
PRINT (N'Create schema [wf]')
GO
IF SCHEMA_ID(N'wf') IS NULL
EXEC sp_executesql N'CREATE SCHEMA wf AUTHORIZATION dbo'
GO

--
-- Create table [wf].[workflow_def]
--
PRINT (N'Create table [wf].[workflow_def]')
GO
IF OBJECT_ID(N'wf.workflow_def', 'U') IS NULL
CREATE TABLE wf.workflow_def (
  id bigint IDENTITY,
  name nvarchar(256) NOT NULL,
  description nvarchar(max) NULL,
  created_at_utc datetime2 NOT NULL CONSTRAINT DF_workflow_def_created DEFAULT (sysutcdatetime()),
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [wf].[workflow_version]
--
PRINT (N'Create table [wf].[workflow_version]')
GO
IF OBJECT_ID(N'wf.workflow_version', 'U') IS NULL
CREATE TABLE wf.workflow_version (
  id bigint IDENTITY,
  workflow_def_id bigint NOT NULL,
  version_major int NOT NULL CONSTRAINT DF_wfv_major DEFAULT (1),
  version_minor int NOT NULL CONSTRAINT DF_wfv_minor DEFAULT (0),
  is_active bit NOT NULL CONSTRAINT DF_wfv_active DEFAULT (1),
  root_node_id bigint NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_wfv_def_version UNIQUE (workflow_def_id, version_major, version_minor)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_wfv_def] on table [wf].[workflow_version]
--
PRINT (N'Create foreign key [FK_wfv_def] on table [wf].[workflow_version]')
GO
IF OBJECT_ID('wf.FK_wfv_def', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_version', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_def', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_def_id' AND object_id = OBJECT_ID(N'wf.workflow_version'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_def'))
ALTER TABLE wf.workflow_version
  ADD CONSTRAINT FK_wfv_def FOREIGN KEY (workflow_def_id) REFERENCES wf.workflow_def (id)
GO

--
-- Create table [wf].[workflow_instance]
--
PRINT (N'Create table [wf].[workflow_instance]')
GO
IF OBJECT_ID(N'wf.workflow_instance', 'U') IS NULL
CREATE TABLE wf.workflow_instance (
  id bigint IDENTITY,
  workflow_version_id bigint NOT NULL,
  status varchar(32) NOT NULL CONSTRAINT DF_wi_status DEFAULT (N'CREATED'),
  context_json json NULL,
  started_at_utc datetime2 NULL,
  completed_at_utc datetime2 NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT CK_wi_status CHECK ([status]=N'CANCELLED' OR [status]=N'FAILED' OR [status]=N'COMPLETED' OR [status]=N'RUNNING' OR [status]=N'CREATED')
)
ON [PRIMARY]
GO

--
-- Create index [IX_wi_version_status] on table [wf].[workflow_instance]
--
PRINT (N'Create index [IX_wi_version_status] on table [wf].[workflow_instance]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_wi_version_status' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_version_id' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'status' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
CREATE INDEX IX_wi_version_status
  ON wf.workflow_instance (workflow_version_id, status)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_wi_version] on table [wf].[workflow_instance]
--
PRINT (N'Create foreign key [FK_wi_version] on table [wf].[workflow_instance]')
GO
IF OBJECT_ID('wf.FK_wi_version', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_instance', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_version', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_version_id' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_version'))
ALTER TABLE wf.workflow_instance
  ADD CONSTRAINT FK_wi_version FOREIGN KEY (workflow_version_id) REFERENCES wf.workflow_version (id)
GO

--
-- Create table [wf].[instance_cursor]
--
PRINT (N'Create table [wf].[instance_cursor]')
GO
IF OBJECT_ID(N'wf.instance_cursor', 'U') IS NULL
CREATE TABLE wf.instance_cursor (
  workflow_instance_id bigint NOT NULL,
  last_polled_at_utc datetime2 NULL,
  notes nvarchar(512) NULL,
  PRIMARY KEY CLUSTERED (workflow_instance_id)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_ic_instance] on table [wf].[instance_cursor]
--
PRINT (N'Create foreign key [FK_ic_instance] on table [wf].[instance_cursor]')
GO
IF OBJECT_ID('wf.FK_ic_instance', 'F') IS NULL
  AND OBJECT_ID('wf.instance_cursor', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_instance', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.instance_cursor'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
ALTER TABLE wf.instance_cursor
  ADD CONSTRAINT FK_ic_instance FOREIGN KEY (workflow_instance_id) REFERENCES wf.workflow_instance (id) ON DELETE CASCADE
GO

--
-- Create table [wf].[workflow_action]
--
PRINT (N'Create table [wf].[workflow_action]')
GO
IF OBJECT_ID(N'wf.workflow_action', 'U') IS NULL
CREATE TABLE wf.workflow_action (
  id bigint IDENTITY,
  action_name nvarchar(256) NOT NULL,
  capability nvarchar(128) NULL,
  payload_schema_ref nvarchar(512) NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_workflow_action_name UNIQUE (action_name)
)
ON [PRIMARY]
GO

--
-- Create table [wf].[workflow_node]
--
PRINT (N'Create table [wf].[workflow_node]')
GO
IF OBJECT_ID(N'wf.workflow_node', 'U') IS NULL
CREATE TABLE wf.workflow_node (
  id bigint IDENTITY,
  workflow_version_id bigint NOT NULL,
  node_type varchar(32) NOT NULL,
  node_key nvarchar(128) NOT NULL,
  workflow_action_id bigint NULL,
  repeat_count int NULL,
  condition_ref_node_key nvarchar(128) NULL,
  switch_ref_node_key nvarchar(128) NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_wn_version_key UNIQUE (workflow_version_id, node_key),
  CONSTRAINT CK_wn_node_type CHECK ([node_type]=N'WHILE' OR [node_type]=N'REPEAT' OR [node_type]=N'SWITCH' OR [node_type]=N'IF' OR [node_type]=N'PARALLEL' OR [node_type]=N'SEQUENCE' OR [node_type]=N'ACTION')
)
ON [PRIMARY]
GO

--
-- Create index [IX_workflow_node_version] on table [wf].[workflow_node]
--
PRINT (N'Create index [IX_workflow_node_version] on table [wf].[workflow_node]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_workflow_node_version' AND object_id = OBJECT_ID(N'wf.workflow_node'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_version_id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
CREATE INDEX IX_workflow_node_version
  ON wf.workflow_node (workflow_version_id)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_wn_action] on table [wf].[workflow_node]
--
PRINT (N'Create foreign key [FK_wn_action] on table [wf].[workflow_node]')
GO
IF OBJECT_ID('wf.FK_wn_action', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_action', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_action_id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_action'))
ALTER TABLE wf.workflow_node
  ADD CONSTRAINT FK_wn_action FOREIGN KEY (workflow_action_id) REFERENCES wf.workflow_action (id)
GO

--
-- Create foreign key [FK_wn_version] on table [wf].[workflow_node]
--
PRINT (N'Create foreign key [FK_wn_version] on table [wf].[workflow_node]')
GO
IF OBJECT_ID('wf.FK_wn_version', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_version', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_version_id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_version'))
ALTER TABLE wf.workflow_node
  ADD CONSTRAINT FK_wn_version FOREIGN KEY (workflow_version_id) REFERENCES wf.workflow_version (id) ON DELETE CASCADE
GO

--
-- Create foreign key [FK_wfv_root] on table [wf].[workflow_version]
--
PRINT (N'Create foreign key [FK_wfv_root] on table [wf].[workflow_version]')
GO
IF OBJECT_ID('wf.FK_wfv_root', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_version', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'root_node_id' AND object_id = OBJECT_ID(N'wf.workflow_version'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.workflow_version WITH NOCHECK
  ADD CONSTRAINT FK_wfv_root FOREIGN KEY (root_node_id) REFERENCES wf.workflow_node (id)
GO

--
-- Create table [wf].[workflow_input_template]
--
PRINT (N'Create table [wf].[workflow_input_template]')
GO
IF OBJECT_ID(N'wf.workflow_input_template', 'U') IS NULL
CREATE TABLE wf.workflow_input_template (
  workflow_node_id bigint NOT NULL,
  template_json json NOT NULL CONSTRAINT DF_wit_template DEFAULT (CAST(N'{}' AS json)),
  PRIMARY KEY CLUSTERED (workflow_node_id)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_wit_node] on table [wf].[workflow_input_template]
--
PRINT (N'Create foreign key [FK_wit_node] on table [wf].[workflow_input_template]')
GO
IF OBJECT_ID('wf.FK_wit_node', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_input_template', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.workflow_input_template'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.workflow_input_template
  ADD CONSTRAINT FK_wit_node FOREIGN KEY (workflow_node_id) REFERENCES wf.workflow_node (id) ON DELETE CASCADE
GO

--
-- Create table [wf].[workflow_input_binding]
--
PRINT (N'Create table [wf].[workflow_input_binding]')
GO
IF OBJECT_ID(N'wf.workflow_input_binding', 'U') IS NULL
CREATE TABLE wf.workflow_input_binding (
  id bigint IDENTITY,
  workflow_node_id bigint NOT NULL,
  target_json_path nvarchar(1024) NOT NULL,
  source_expr nvarchar(1024) NOT NULL,
  is_required bit NOT NULL CONSTRAINT DF_wib_required DEFAULT (0),
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create index [IX_wib_node] on table [wf].[workflow_input_binding]
--
PRINT (N'Create index [IX_wib_node] on table [wf].[workflow_input_binding]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_wib_node' AND object_id = OBJECT_ID(N'wf.workflow_input_binding'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.workflow_input_binding'))
CREATE INDEX IX_wib_node
  ON wf.workflow_input_binding (workflow_node_id)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_wib_node] on table [wf].[workflow_input_binding]
--
PRINT (N'Create foreign key [FK_wib_node] on table [wf].[workflow_input_binding]')
GO
IF OBJECT_ID('wf.FK_wib_node', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_input_binding', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.workflow_input_binding'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.workflow_input_binding
  ADD CONSTRAINT FK_wib_node FOREIGN KEY (workflow_node_id) REFERENCES wf.workflow_node (id) ON DELETE CASCADE
GO

--
-- Create table [wf].[workflow_edge]
--
PRINT (N'Create table [wf].[workflow_edge]')
GO
IF OBJECT_ID(N'wf.workflow_edge', 'U') IS NULL
CREATE TABLE wf.workflow_edge (
  id bigint IDENTITY,
  parent_node_id bigint NOT NULL,
  child_node_id bigint NOT NULL,
  child_order int NOT NULL CONSTRAINT DF_we_child_order DEFAULT (0),
  branch_kind varchar(32) NULL,
  condition_expr nvarchar(max) NULL,
  switch_case_value int NULL,
  is_default bit NOT NULL CONSTRAINT DF_we_default DEFAULT (0),
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT CK_we_branch_kind CHECK ([branch_kind] IS NULL OR ([branch_kind]=N'BODY' OR [branch_kind]=N'DEFAULT' OR [branch_kind]=N'CASE' OR [branch_kind]=N'ELSE' OR [branch_kind]=N'THEN' OR [branch_kind]=N'PARALLEL' OR [branch_kind]=N'SEQUENCE')),
  CONSTRAINT CK_we_no_self_loop CHECK ([parent_node_id]<>[child_node_id])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index [IX_we_child] on table [wf].[workflow_edge]
--
PRINT (N'Create index [IX_we_child] on table [wf].[workflow_edge]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_we_child' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'child_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
CREATE INDEX IX_we_child
  ON wf.workflow_edge (child_node_id)
  ON [PRIMARY]
GO

--
-- Create index [IX_we_parent] on table [wf].[workflow_edge]
--
PRINT (N'Create index [IX_we_parent] on table [wf].[workflow_edge]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_we_parent' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'parent_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
CREATE INDEX IX_we_parent
  ON wf.workflow_edge (parent_node_id)
  ON [PRIMARY]
GO

--
-- Create index [UQ_we_parent_child] on table [wf].[workflow_edge]
--
PRINT (N'Create index [UQ_we_parent_child] on table [wf].[workflow_edge]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'UQ_we_parent_child' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'parent_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'child_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
CREATE UNIQUE INDEX UQ_we_parent_child
  ON wf.workflow_edge (parent_node_id, child_node_id)
  ON [PRIMARY]
GO

--
-- UQ_we_parent_child_order is intentionally absent.
-- IF THEN/ELSE (and similar) share child_order=0; uniqueness is parent+child
-- (UQ_we_parent_child). See wf_workflow_edge_index_fixup.sql.
--
PRINT (N'Skip unique index [UQ_we_parent_child_order] (IF THEN/ELSE share child_order)')
GO
IF EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'UQ_we_parent_child_order' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
    DROP INDEX UQ_we_parent_child_order ON wf.workflow_edge;
GO

--
-- Create foreign key [FK_we_child] on table [wf].[workflow_edge]
--
PRINT (N'Create foreign key [FK_we_child] on table [wf].[workflow_edge]')
GO
IF OBJECT_ID('wf.FK_we_child', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_edge', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'child_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.workflow_edge
  ADD CONSTRAINT FK_we_child FOREIGN KEY (child_node_id) REFERENCES wf.workflow_node (id)
GO

--
-- Create foreign key [FK_we_parent] on table [wf].[workflow_edge]
--
PRINT (N'Create foreign key [FK_we_parent] on table [wf].[workflow_edge]')
GO
IF OBJECT_ID('wf.FK_we_parent', 'F') IS NULL
  AND OBJECT_ID('wf.workflow_edge', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'parent_node_id' AND object_id = OBJECT_ID(N'wf.workflow_edge'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.workflow_edge
  ADD CONSTRAINT FK_we_parent FOREIGN KEY (parent_node_id) REFERENCES wf.workflow_node (id)
GO

--
-- Create table [wf].[node_execution]
--
PRINT (N'Create table [wf].[node_execution]')
GO
IF OBJECT_ID(N'wf.node_execution', 'U') IS NULL
CREATE TABLE wf.node_execution (
  id bigint IDENTITY,
  workflow_instance_id bigint NOT NULL,
  workflow_node_id bigint NOT NULL,
  status varchar(32) NOT NULL CONSTRAINT DF_ne_status DEFAULT (N'PENDING'),
  attempt_no int NOT NULL CONSTRAINT DF_ne_attempt DEFAULT (1),
  parent_node_execution_id bigint NULL,
  iteration_no int NOT NULL CONSTRAINT DF_ne_iter DEFAULT (0),
  input_json json NULL,
  output_json json NULL,
  result_code int NULL,
  engine_error_code int NULL,
  engine_error_message nvarchar(1024) NULL,
  started_at_utc datetime2 NULL,
  ended_at_utc datetime2 NULL,
  available_at_utc datetime2 NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT CK_ne_status CHECK ([status]=N'CANCELLED' OR [status]=N'SKIPPED' OR [status]=N'FAILED' OR [status]=N'SUCCEEDED' OR [status]=N'RUNNING' OR [status]=N'READY' OR [status]=N'PENDING')
)
ON [PRIMARY]
GO

--
-- Ensure [wf].[node_execution] JSON payload columns are native JSON
--
PRINT (N'Ensure JSON columns on [wf].[node_execution]')
GO
IF OBJECT_ID(N'wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM sys.columns c
    JOIN sys.types t ON t.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'wf.node_execution')
      AND c.name = N'input_json'
      AND t.name <> N'json'
  )
ALTER TABLE wf.node_execution ALTER COLUMN input_json json NULL
GO
IF OBJECT_ID(N'wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM sys.columns c
    JOIN sys.types t ON t.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'wf.node_execution')
      AND c.name = N'output_json'
      AND t.name <> N'json'
  )
  AND EXISTS (
    SELECT 1
    FROM sys.indexes WITH (NOLOCK)
    WHERE name = N'IX_ne_instance_status_ended'
      AND object_id = OBJECT_ID(N'wf.node_execution')
  )
DROP INDEX IX_ne_instance_status_ended ON wf.node_execution
GO
IF OBJECT_ID(N'wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM sys.columns c
    JOIN sys.types t ON t.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'wf.node_execution')
      AND c.name = N'output_json'
      AND t.name <> N'json'
  )
ALTER TABLE wf.node_execution ALTER COLUMN output_json json NULL
GO

--
-- Create index [IX_ne_instance_node] on table [wf].[node_execution]
--
PRINT (N'Create index [IX_ne_instance_node] on table [wf].[node_execution]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ne_instance_node' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'status' AND object_id = OBJECT_ID(N'wf.node_execution'))
CREATE INDEX IX_ne_instance_node
  ON wf.node_execution (workflow_instance_id, workflow_node_id, status)
  ON [PRIMARY]
GO

--
-- Create index [IX_ne_instance_status_avail] on table [wf].[node_execution]
--
PRINT (N'Create index [IX_ne_instance_status_avail] on table [wf].[node_execution]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ne_instance_status_avail' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'status' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'available_at_utc' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
CREATE INDEX IX_ne_instance_status_avail
  ON wf.node_execution (workflow_instance_id, status, available_at_utc)
  INCLUDE (workflow_node_id)
  ON [PRIMARY]
GO

--
-- Create index [IX_ne_instance_status_ended] on table [wf].[node_execution]
--
PRINT (N'Create index [IX_ne_instance_status_ended] on table [wf].[node_execution]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ne_instance_status_ended' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'status' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ended_at_utc' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'result_code' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'output_json' AND object_id = OBJECT_ID(N'wf.node_execution'))
CREATE INDEX IX_ne_instance_status_ended
  ON wf.node_execution (workflow_instance_id, status, ended_at_utc DESC)
  INCLUDE (workflow_node_id, result_code, output_json)
  ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON
GO

--
-- Create index [IX_ne_ready_worker_poll] on table [wf].[node_execution]
--
PRINT (N'Create index [IX_ne_ready_worker_poll] on table [wf].[node_execution]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ne_ready_worker_poll' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'status' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'available_at_utc' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
CREATE INDEX IX_ne_ready_worker_poll
  ON wf.node_execution (status, available_at_utc)
  INCLUDE (workflow_instance_id, workflow_node_id)
  WHERE ([status] IN ('READY', 'RUNNING'))
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_ne_instance] on table [wf].[node_execution]
--
PRINT (N'Create foreign key [FK_ne_instance] on table [wf].[node_execution]')
GO
IF OBJECT_ID('wf.FK_ne_instance', 'F') IS NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_instance', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
ALTER TABLE wf.node_execution
  ADD CONSTRAINT FK_ne_instance FOREIGN KEY (workflow_instance_id) REFERENCES wf.workflow_instance (id) ON DELETE CASCADE
GO

--
-- Create foreign key [FK_ne_node] on table [wf].[node_execution]
--
PRINT (N'Create foreign key [FK_ne_node] on table [wf].[node_execution]')
GO
IF OBJECT_ID('wf.FK_ne_node', 'F') IS NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_node_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.node_execution
  ADD CONSTRAINT FK_ne_node FOREIGN KEY (workflow_node_id) REFERENCES wf.workflow_node (id)
GO

--
-- Create foreign key [FK_ne_parent_exec] on table [wf].[node_execution]
--
PRINT (N'Create foreign key [FK_ne_parent_exec] on table [wf].[node_execution]')
GO
IF OBJECT_ID('wf.FK_ne_parent_exec', 'F') IS NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'parent_node_execution_id' AND object_id = OBJECT_ID(N'wf.node_execution'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.node_execution'))
ALTER TABLE wf.node_execution
  ADD CONSTRAINT FK_ne_parent_exec FOREIGN KEY (parent_node_execution_id) REFERENCES wf.node_execution (id)
GO

SET ANSI_NULLS ON
GO

--
-- Create or alter function [wf].[wf_try_task_result_code]
--
GO
PRINT (N'Create or alter function [wf].[wf_try_task_result_code]')
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WITH (NOLOCK) WHERE object_id = OBJECT_ID(N'wf.wf_try_task_result_code') AND type IN ('IF', 'FN', 'TF'))
EXEC sp_executesql N'
CREATE OR ALTER FUNCTION wf.wf_try_task_result_code(@workflow_instance_id BIGINT, @node_key NVARCHAR(128))
RETURNS INT
AS
BEGIN
    DECLARE @r INT;
    SELECT TOP (1) @r = ne.result_code
    FROM wf.node_execution AS ne
    INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
    WHERE ne.workflow_instance_id = @workflow_instance_id
      AND wn.node_key = @node_key
      AND ne.status = N''SUCCEEDED''
    ORDER BY ne.ended_at_utc DESC, ne.id DESC;
    RETURN @r;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_while_continue]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_while_continue]')
GO
IF OBJECT_ID(N'wf.wf_while_continue', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_while_continue
    @while_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @workflow_instance_id BIGINT;
    DECLARE @inst BIGINT;
    DECLARE @ctl BIGINT;
    SELECT @inst = workflow_instance_id, @ctl = workflow_node_id FROM wf.node_execution WHERE id = @while_execution_id;

    DECLARE @wcref NVARCHAR(128);
    SELECT @wcref = condition_ref_node_key FROM wf.workflow_node WHERE id = @ctl;

    DECLARE @wcond INT = wf.wf_try_task_result_code(@workflow_instance_id, @wcref);

    IF @wcond IS NULL OR @wcond = 0
    BEGIN
        UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @while_execution_id;
        EXEC wf.wf_engine_on_composite_complete @node_execution_id = @while_execution_id;
        RETURN;
    END

    DECLARE @iter INT = ISNULL((SELECT MAX(iteration_no) FROM wf.node_execution WHERE parent_node_execution_id = @while_execution_id AND workflow_node_id = (
        SELECT TOP (1) child_node_id FROM wf.workflow_edge WHERE parent_node_id = @ctl AND branch_kind = N''BODY'' ORDER BY child_order ASC
    )), 0);

    DECLARE @wbody BIGINT;
    SELECT TOP (1) @wbody = child_node_id FROM wf.workflow_edge WHERE parent_node_id = @ctl AND branch_kind = N''BODY'' ORDER BY child_order ASC;

    DECLARE @iter1 INT = @iter + 1;
    EXEC wf.wf_engine_activate
        @workflow_instance_id = @inst,
        @workflow_node_id = @wbody,
        @parent_node_execution_id = @while_execution_id,
        @iteration_no = @iter1,
        @sequence_index = NULL,
        @parallel_index = NULL;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_sequence_continue]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_sequence_continue]')
GO
IF OBJECT_ID(N'wf.wf_sequence_continue', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_sequence_continue
    @sequence_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inst BIGINT;
    DECLARE @seq_node BIGINT;
    SELECT @inst = workflow_instance_id, @seq_node = workflow_node_id FROM wf.node_execution WHERE id = @sequence_execution_id;

    DECLARE @last_child_ne BIGINT;
    SELECT TOP (1) @last_child_ne = ne.id
    FROM wf.node_execution AS ne
    WHERE ne.parent_node_execution_id = @sequence_execution_id AND ne.status IN (N''SUCCEEDED'', N''FAILED'', N''SKIPPED'')
    ORDER BY ne.ended_at_utc DESC, ne.id DESC;

    DECLARE @last_status VARCHAR(32);
    DECLARE @last_child_wn BIGINT;
    SELECT @last_child_wn = workflow_node_id, @last_status = status FROM wf.node_execution WHERE id = @last_child_ne;

    IF @last_status = N''FAILED''
    BEGIN
        UPDATE wf.node_execution SET status = N''FAILED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @sequence_execution_id;
        UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @inst;
        RETURN;
    END

    DECLARE @next_order INT;
    SELECT @next_order = e.child_order + 1
    FROM wf.workflow_edge AS e
    WHERE e.parent_node_id = @seq_node AND e.child_node_id = @last_child_wn;

    DECLARE @next_child BIGINT;
    SELECT TOP (1) @next_child = child_node_id
    FROM wf.workflow_edge
    WHERE parent_node_id = @seq_node AND child_order = @next_order;

    IF @next_child IS NULL
    BEGIN
        UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @sequence_execution_id;
        EXEC wf.wf_engine_on_composite_complete @node_execution_id = @sequence_execution_id;
        RETURN;
    END;

    DECLARE @iter INT = (SELECT iteration_no FROM wf.node_execution WHERE id = @sequence_execution_id);
    EXEC wf.wf_engine_activate
        @workflow_instance_id = @inst,
        @workflow_node_id = @next_child,
        @parent_node_execution_id = @sequence_execution_id,
        @iteration_no = @iter,
        @sequence_index = @next_order,
        @parallel_index = NULL;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_parallel_continue]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_parallel_continue]')
GO
IF OBJECT_ID(N'wf.wf_parallel_continue', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_parallel_continue
    @parallel_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inst BIGINT;
    DECLARE @pnode BIGINT;
    SELECT @inst = workflow_instance_id, @pnode = workflow_node_id FROM wf.node_execution WHERE id = @parallel_execution_id;

    DECLARE @total INT = (SELECT COUNT(*) FROM wf.workflow_edge WHERE parent_node_id = @pnode);

    DECLARE @finished INT = (
        SELECT COUNT(*)
        FROM wf.node_execution AS ne
        WHERE ne.parent_node_execution_id = @parallel_execution_id
          AND ne.status IN (N''SUCCEEDED'', N''FAILED'', N''SKIPPED'', N''CANCELLED'')
    );

    IF @finished < @total RETURN;

    IF EXISTS (
        SELECT 1 FROM wf.node_execution
        WHERE parent_node_execution_id = @parallel_execution_id AND status = N''FAILED''
    )
    BEGIN
        UPDATE wf.node_execution SET status = N''FAILED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @parallel_execution_id;
        UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @inst;
        RETURN;
    END

    UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @parallel_execution_id;
    EXEC wf.wf_engine_on_composite_complete @node_execution_id = @parallel_execution_id;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_engine_on_composite_complete]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_engine_on_composite_complete]')
GO
IF OBJECT_ID(N'wf.wf_engine_on_composite_complete', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_engine_on_composite_complete
    @node_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @parent BIGINT;
    DECLARE @inst BIGINT;
    SELECT @parent = parent_node_execution_id, @inst = workflow_instance_id FROM wf.node_execution WHERE id = @node_execution_id;

    IF @parent IS NULL
    BEGIN
        UPDATE wf.workflow_instance
        SET status = N''COMPLETED'', completed_at_utc = SYSUTCDATETIME()
        WHERE id = @inst AND status = N''RUNNING'';
        RETURN;
    END

    EXEC wf.wf_engine_continue_parent @parent_node_execution_id = @parent;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_engine_continue_parent]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_engine_continue_parent]')
GO
IF OBJECT_ID(N'wf.wf_engine_continue_parent', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_engine_continue_parent
    @parent_node_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @pnode BIGINT;
    DECLARE @ptype VARCHAR(32);
    SELECT @pnode = ne.workflow_node_id, @ptype = wn.node_type
    FROM wf.node_execution AS ne
    INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
    WHERE ne.id = @parent_node_execution_id;

    IF @ptype = N''SEQUENCE''
        EXEC wf.wf_sequence_continue @sequence_execution_id = @parent_node_execution_id;

    ELSE IF @ptype = N''PARALLEL''
        EXEC wf.wf_parallel_continue @parallel_execution_id = @parent_node_execution_id;

    ELSE IF @ptype IN (N''IF'', N''SWITCH'')
    BEGIN
        UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @parent_node_execution_id;
        EXEC wf.wf_engine_on_composite_complete @node_execution_id = @parent_node_execution_id;
    END

    ELSE IF @ptype = N''REPEAT''
        EXEC wf.wf_repeat_continue @repeat_execution_id = @parent_node_execution_id;

    ELSE IF @ptype = N''WHILE''
        EXEC wf.wf_while_continue @while_execution_id = @parent_node_execution_id;

    /* FOREACH arrives with wf_sql_foreach_support.sql; dispatch through the router so
       re-running this base script never drops FOREACH continuation. */
    ELSE IF @ptype = N''FOREACH''
        EXEC wf.wf_foreach_route_continue @foreach_execution_id = @parent_node_execution_id;
END;
'
GO

--
-- Create table [wf].[cluster]
--
PRINT (N'Create table [wf].[cluster]')
GO
IF OBJECT_ID(N'wf.cluster', 'U') IS NULL
CREATE TABLE wf.cluster (
  id bigint IDENTITY NOT NULL,
  cluster_key nvarchar(128) NOT NULL,
  name nvarchar(256) NOT NULL,
  provider nvarchar(64) NULL,
  shared_storage_uri nvarchar(1024) NULL,
  worker_mount_path nvarchar(256) NOT NULL CONSTRAINT DF_cluster_mount DEFAULT (N'/work'),
  status varchar(32) NOT NULL CONSTRAINT DF_cluster_status DEFAULT (N'ACTIVE'),
  created_at_utc datetime2 NOT NULL CONSTRAINT DF_cluster_created DEFAULT (SYSUTCDATETIME()),
  updated_at_utc datetime2 NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_cluster_key UNIQUE (cluster_key),
  CONSTRAINT CK_cluster_status CHECK ([status]=N'DISABLED' OR [status]=N'ACTIVE')
)
ON [PRIMARY]
GO

--
-- Create table [wf].[worker]
--
PRINT (N'Create table [wf].[worker]')
GO
IF OBJECT_ID(N'wf.worker', 'U') IS NULL
CREATE TABLE wf.worker (
  id bigint IDENTITY NOT NULL,
  cluster_id bigint NOT NULL,
  external_worker_key nvarchar(128) NULL,
  display_name nvarchar(256) NULL,
  hostname nvarchar(256) NULL,
  capabilities json NULL,
  status varchar(32) NOT NULL CONSTRAINT DF_worker_status DEFAULT (N'REGISTERED'),
  last_seen_at_utc datetime2 NULL,
  created_at_utc datetime2 NOT NULL CONSTRAINT DF_worker_created DEFAULT (SYSUTCDATETIME()),
  updated_at_utc datetime2 NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT FK_worker_cluster FOREIGN KEY (cluster_id) REFERENCES wf.cluster (id),
  CONSTRAINT UQ_worker_external_key UNIQUE (external_worker_key),
  CONSTRAINT CK_worker_status CHECK ([status]=N'REVOKED' OR [status]=N'SUSPENDED' OR [status]=N'REGISTERED')
)
ON [PRIMARY]
GO

--
-- Create index [IX_worker_cluster_status] on table [wf].[worker]
--
PRINT (N'Create index [IX_worker_cluster_status] on table [wf].[worker]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_worker_cluster_status' AND object_id = OBJECT_ID(N'wf.worker'))
  AND OBJECT_ID(N'wf.worker', 'U') IS NOT NULL
CREATE INDEX IX_worker_cluster_status
  ON wf.worker (cluster_id, status)
  ON [PRIMARY]
GO

--
-- Create table [wf].[worker_token]
--
PRINT (N'Create table [wf].[worker_token]')
GO
IF OBJECT_ID(N'wf.worker_token', 'U') IS NULL
CREATE TABLE wf.worker_token (
  id bigint IDENTITY NOT NULL,
  worker_id bigint NOT NULL,
  token_hash varbinary(32) NOT NULL,
  token_prefix nvarchar(16) NULL,
  issued_at_utc datetime2 NOT NULL CONSTRAINT DF_wt_issued DEFAULT (SYSUTCDATETIME()),
  expires_at_utc datetime2 NULL,
  revoked_at_utc datetime2 NULL,
  status varchar(32) NOT NULL CONSTRAINT DF_wt_status DEFAULT (N'ACTIVE'),
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_wt_worker_hash UNIQUE (worker_id, token_hash),
  CONSTRAINT FK_wt_worker FOREIGN KEY (worker_id) REFERENCES wf.worker (id) ON DELETE CASCADE,
  CONSTRAINT CK_wt_status CHECK ([status]=N'REVOKED' OR [status]=N'EXPIRED' OR [status]=N'ACTIVE')
)
ON [PRIMARY]
GO

--
-- Create table [wf].[task_lease]
--
PRINT (N'Create table [wf].[task_lease]')
GO
IF OBJECT_ID(N'wf.task_lease', 'U') IS NULL
CREATE TABLE wf.task_lease (
  node_execution_id bigint NOT NULL,
  worker_id bigint NOT NULL,
  lease_expires_at_utc datetime2 NOT NULL,
  heartbeat_at_utc datetime2 NULL,
  PRIMARY KEY CLUSTERED (node_execution_id)
)
ON [PRIMARY]
GO

--
-- Create index [IX_tl_worker_expiry] on table [wf].[task_lease]
--
PRINT (N'Create index [IX_tl_worker_expiry] on table [wf].[task_lease]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_tl_worker_expiry' AND object_id = OBJECT_ID(N'wf.task_lease'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'worker_id' AND object_id = OBJECT_ID(N'wf.task_lease'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'lease_expires_at_utc' AND object_id = OBJECT_ID(N'wf.task_lease'))
CREATE INDEX IX_tl_worker_expiry
  ON wf.task_lease (worker_id, lease_expires_at_utc)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_tl_ne] on table [wf].[task_lease]
--
PRINT (N'Create foreign key [FK_tl_ne] on table [wf].[task_lease]')
GO
IF OBJECT_ID('wf.FK_tl_ne', 'F') IS NULL
  AND OBJECT_ID('wf.task_lease', 'U') IS NOT NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'node_execution_id' AND object_id = OBJECT_ID(N'wf.task_lease'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.node_execution'))
ALTER TABLE wf.task_lease
  ADD CONSTRAINT FK_tl_ne FOREIGN KEY (node_execution_id) REFERENCES wf.node_execution (id) ON DELETE CASCADE
GO

--
-- Create foreign key [FK_tl_worker] on table [wf].[task_lease]
--
PRINT (N'Create foreign key [FK_tl_worker] on table [wf].[task_lease]')
GO
IF OBJECT_ID('wf.FK_tl_worker', 'F') IS NULL
  AND OBJECT_ID('wf.task_lease', 'U') IS NOT NULL
  AND OBJECT_ID('wf.worker', 'U') IS NOT NULL
ALTER TABLE wf.task_lease
  ADD CONSTRAINT FK_tl_worker FOREIGN KEY (worker_id) REFERENCES wf.worker (id)
GO

--
-- Create or alter procedure [wf].[wf_worker_authenticate]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_worker_authenticate]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_worker_authenticate
    @worker_id BIGINT,
    @worker_token NVARCHAR(4000)
AS
BEGIN
    SET NOCOUNT ON;

    IF @worker_id IS NULL
        THROW 50002, N''worker_id is required.'', 1;

    DECLARE @tok NVARCHAR(4000) = NULLIF(LTRIM(RTRIM(@worker_token)), N'''');
    IF @tok IS NULL
        THROW 50002, N''worker_token is required.'', 1;

    DECLARE @hash VARBINARY(32) = HASHBYTES(N''SHA2_256'', @tok);

    IF NOT EXISTS (
        SELECT 1
        FROM wf.worker_token AS wt
        INNER JOIN wf.worker AS w ON w.id = wt.worker_id
        INNER JOIN wf.cluster AS c ON c.id = w.cluster_id
        WHERE wt.worker_id = @worker_id
          AND wt.token_hash = @hash
          AND wt.status = N''ACTIVE''
          AND (wt.expires_at_utc IS NULL OR wt.expires_at_utc > SYSUTCDATETIME())
          AND w.status = N''REGISTERED''
          AND c.status = N''ACTIVE''
    )
        THROW 50003, N''Invalid or unauthorized worker credentials.'', 1;

    UPDATE wf.worker
    SET last_seen_at_utc = SYSUTCDATETIME()
    WHERE id = @worker_id;
END;
'
GO

--
-- Create or alter procedure [wf].[sp_worker_request_task]
--
GO
PRINT (N'Create or alter functions for worker capability dispatch')
GO
/* CREATE OR ALTER cannot change NVARCHAR → json; drop dependents first. */
IF OBJECT_ID(N'wf.sp_worker_request_task', N'P') IS NOT NULL
    DROP PROCEDURE wf.sp_worker_request_task;
IF OBJECT_ID(N'wf.wf_worker_capability_allowed', N'FN') IS NOT NULL
    DROP FUNCTION wf.wf_worker_capability_allowed;
IF OBJECT_ID(N'wf.wf_worker_is_omnibus', N'FN') IS NOT NULL
    DROP FUNCTION wf.wf_worker_is_omnibus;
GO
EXEC sp_executesql N'
CREATE OR ALTER FUNCTION wf.wf_worker_is_omnibus(@capabilities json)
RETURNS BIT
AS
BEGIN
    IF @capabilities IS NULL
        RETURN 0;
    IF NOT EXISTS (SELECT 1 FROM OPENJSON(@capabilities))
        RETURN 0;
    IF EXISTS (
        SELECT 1
        FROM OPENJSON(@capabilities) WITH (value NVARCHAR(128) ''$'') AS caps
        WHERE caps.value = N''*''
    )
        RETURN 1;
    RETURN 0;
END;
'
GO
EXEC sp_executesql N'
CREATE OR ALTER FUNCTION wf.wf_worker_capability_allowed(
    @worker_capabilities json,
    @task_capability NVARCHAR(128)
)
RETURNS BIT
AS
BEGIN
    IF @task_capability IS NULL
        RETURN 1;
    IF wf.wf_worker_is_omnibus(@worker_capabilities) = 1
        RETURN 1;
    IF EXISTS (
        SELECT 1
        FROM OPENJSON(@worker_capabilities) WITH (value NVARCHAR(128) ''$'') AS caps
        WHERE caps.value = @task_capability
    )
        RETURN 1;
    RETURN 0;
END;
'
GO
PRINT (N'Create or alter procedure [wf].[sp_worker_request_task]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.sp_worker_request_task
    @worker_id BIGINT,
    @worker_token NVARCHAR(4000),
    @capability NVARCHAR(128) NULL,
    @max_lease_seconds INT = 300
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    EXEC wf.wf_worker_authenticate @worker_id = @worker_id, @worker_token = @worker_token;

    DECLARE @now DATETIME2(7) = SYSUTCDATETIME();
    DECLARE @lease_end DATETIME2(7) = DATEADD(SECOND, @max_lease_seconds, @now);
    DECLARE @worker_capabilities json;
    DECLARE @is_omnibus BIT;

    SELECT @worker_capabilities = w.capabilities
    FROM wf.worker AS w
    WHERE w.id = @worker_id;

    SET @is_omnibus = wf.wf_worker_is_omnibus(@worker_capabilities);

    IF @capability IS NOT NULL
       AND @is_omnibus = 0
       AND wf.wf_worker_capability_allowed(@worker_capabilities, @capability) = 0
    BEGIN
        RETURN;
    END

    BEGIN TRANSACTION;

    DECLARE @picked_ids TABLE (id BIGINT);

    ;WITH cte AS (
        SELECT TOP (1) ne.id
        FROM wf.node_execution AS ne WITH (ROWLOCK, READPAST, UPDLOCK)
        INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
        INNER JOIN wf.workflow_action AS wa ON wa.id = wn.workflow_action_id
        INNER JOIN wf.workflow_instance AS wi ON wi.id = ne.workflow_instance_id
        WHERE ne.status = N''READY''
          AND wn.node_type = N''ACTION''
          AND wi.status = N''RUNNING''
          AND (ne.available_at_utc IS NULL OR ne.available_at_utc <= @now)
          AND wf.wf_worker_capability_allowed(@worker_capabilities, wa.capability) = 1
          AND (
              @capability IS NULL
              OR wa.capability = @capability
              OR wa.capability IS NULL
          )
        ORDER BY ne.available_at_utc ASC, ne.id ASC
    )
    UPDATE ne
    SET status = N''RUNNING'',
        started_at_utc = @now
    OUTPUT inserted.id INTO @picked_ids(id)
    FROM wf.node_execution AS ne
    INNER JOIN cte ON cte.id = ne.id;

    DECLARE @picked BIGINT;
    SELECT @picked = id FROM @picked_ids;

    IF @picked IS NULL
    BEGIN
        ROLLBACK TRANSACTION;
        RETURN;
    END

    ;MERGE wf.task_lease AS t
    USING (SELECT @picked AS node_execution_id) AS s ON (t.node_execution_id = s.node_execution_id)
    WHEN MATCHED THEN
        UPDATE SET worker_id = @worker_id, lease_expires_at_utc = @lease_end, heartbeat_at_utc = @now
    WHEN NOT MATCHED THEN
        INSERT (node_execution_id, worker_id, lease_expires_at_utc, heartbeat_at_utc)
        VALUES (@picked, @worker_id, @lease_end, @now);

    COMMIT TRANSACTION;

    SELECT
        ne.id AS node_execution_id,
        ne.workflow_instance_id,
        wn.node_key,
        wa.action_name,
        wa.capability,
        ne.attempt_no,
        ne.input_json,
        ne.iteration_no
    FROM wf.node_execution AS ne
    INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
    INNER JOIN wf.workflow_action AS wa ON wa.id = wn.workflow_action_id
    WHERE ne.id = @picked;
END;
'
GO

--
-- Create or alter procedure [wf].[sp_worker_heartbeat]
--
GO
PRINT (N'Create or alter procedure [wf].[sp_worker_heartbeat]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.sp_worker_heartbeat
    @node_execution_id BIGINT,
    @worker_id BIGINT,
    @worker_token NVARCHAR(4000),
    @extend_seconds INT = 300
AS
BEGIN
    SET NOCOUNT ON;

    EXEC wf.wf_worker_authenticate @worker_id = @worker_id, @worker_token = @worker_token;

    DECLARE @now DATETIME2(7) = SYSUTCDATETIME();

    UPDATE tl
    SET lease_expires_at_utc = DATEADD(SECOND, @extend_seconds, @now),
        heartbeat_at_utc = @now
    FROM wf.task_lease AS tl
    WHERE tl.node_execution_id = @node_execution_id AND tl.worker_id = @worker_id;

    SELECT @@ROWCOUNT AS rows_updated;
END;
'
GO

--
-- Create or alter procedure [wf].[sp_worker_fail_task]
--
GO
PRINT (N'Create or alter procedure [wf].[sp_worker_fail_task]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.sp_worker_fail_task
    @node_execution_id BIGINT,
    @worker_id BIGINT,
    @worker_token NVARCHAR(4000),
    @error_code INT,
    @error_message NVARCHAR(1024) NULL
AS
BEGIN
    SET NOCOUNT ON;

    EXEC wf.wf_worker_authenticate @worker_id = @worker_id, @worker_token = @worker_token;

    IF NOT EXISTS (
        SELECT 1 FROM wf.task_lease WHERE node_execution_id = @node_execution_id AND worker_id = @worker_id
    )
        RETURN;

    UPDATE wf.node_execution
    SET status = N''FAILED'',
        engine_error_code = @error_code,
        engine_error_message = @error_message,
        ended_at_utc = SYSUTCDATETIME()
    WHERE id = @node_execution_id AND status = N''RUNNING'';

    DELETE FROM wf.task_lease WHERE node_execution_id = @node_execution_id;

    UPDATE wf.workflow_instance
    SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME()
    WHERE id = (SELECT workflow_instance_id FROM wf.node_execution WHERE id = @node_execution_id);
END;
'
GO

--
-- Create table [wf].[loop_state]
--
PRINT (N'Create table [wf].[loop_state]')
GO
IF OBJECT_ID(N'wf.loop_state', 'U') IS NULL
CREATE TABLE wf.loop_state (
  id bigint IDENTITY,
  workflow_instance_id bigint NOT NULL,
  control_node_id bigint NOT NULL,
  scope_node_execution_id bigint NOT NULL,
  current_iteration int NOT NULL CONSTRAINT DF_ls_cur DEFAULT (0),
  repeat_target_count int NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_ls_scope UNIQUE (scope_node_execution_id)
)
ON [PRIMARY]
GO

--
-- Create index [IX_ls_instance] on table [wf].[loop_state]
--
PRINT (N'Create index [IX_ls_instance] on table [wf].[loop_state]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ls_instance' AND object_id = OBJECT_ID(N'wf.loop_state'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.loop_state'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'control_node_id' AND object_id = OBJECT_ID(N'wf.loop_state'))
CREATE INDEX IX_ls_instance
  ON wf.loop_state (workflow_instance_id, control_node_id)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_ls_control] on table [wf].[loop_state]
--
PRINT (N'Create foreign key [FK_ls_control] on table [wf].[loop_state]')
GO
IF OBJECT_ID('wf.FK_ls_control', 'F') IS NULL
  AND OBJECT_ID('wf.loop_state', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_node', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'control_node_id' AND object_id = OBJECT_ID(N'wf.loop_state'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_node'))
ALTER TABLE wf.loop_state
  ADD CONSTRAINT FK_ls_control FOREIGN KEY (control_node_id) REFERENCES wf.workflow_node (id)
GO

--
-- Create foreign key [FK_ls_instance] on table [wf].[loop_state]
--
PRINT (N'Create foreign key [FK_ls_instance] on table [wf].[loop_state]')
GO
IF OBJECT_ID('wf.FK_ls_instance', 'F') IS NULL
  AND OBJECT_ID('wf.loop_state', 'U') IS NOT NULL
  AND OBJECT_ID('wf.workflow_instance', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'workflow_instance_id' AND object_id = OBJECT_ID(N'wf.loop_state'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.workflow_instance'))
ALTER TABLE wf.loop_state
  ADD CONSTRAINT FK_ls_instance FOREIGN KEY (workflow_instance_id) REFERENCES wf.workflow_instance (id)
GO

--
-- Create foreign key [FK_ls_scope] on table [wf].[loop_state]
--
PRINT (N'Create foreign key [FK_ls_scope] on table [wf].[loop_state]')
GO
IF OBJECT_ID('wf.FK_ls_scope', 'F') IS NULL
  AND OBJECT_ID('wf.loop_state', 'U') IS NOT NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'scope_node_execution_id' AND object_id = OBJECT_ID(N'wf.loop_state'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.node_execution'))
ALTER TABLE wf.loop_state
  ADD CONSTRAINT FK_ls_scope FOREIGN KEY (scope_node_execution_id) REFERENCES wf.node_execution (id)
GO

--
-- Create or alter procedure [wf].[wf_repeat_continue]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_repeat_continue]')
GO
IF OBJECT_ID(N'wf.wf_repeat_continue', 'P') IS NULL
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_repeat_continue
    @repeat_execution_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inst BIGINT;
    DECLARE @ctl BIGINT;
    DECLARE @ls BIGINT;
    DECLARE @cur INT;
    DECLARE @max INT;

    SELECT @inst = workflow_instance_id, @ctl = workflow_node_id FROM wf.node_execution WHERE id = @repeat_execution_id;
    SELECT TOP (1)
        @ls = id,
        @cur = current_iteration,
        @max = repeat_target_count
    FROM wf.loop_state
    WHERE scope_node_execution_id = @repeat_execution_id;

    IF @ls IS NULL
    BEGIN
        UPDATE wf.node_execution SET status = N''FAILED'', engine_error_code = 10007, ended_at_utc = SYSUTCDATETIME() WHERE id = @repeat_execution_id;
        UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @inst;
        RETURN;
    END

    SET @cur += 1;
    UPDATE wf.loop_state SET current_iteration = @cur WHERE id = @ls;

    IF @cur >= @max
    BEGIN
        UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @repeat_execution_id;
        EXEC wf.wf_engine_on_composite_complete @node_execution_id = @repeat_execution_id;
        RETURN;
    END

    DECLARE @body BIGINT;
    SELECT TOP (1) @body = child_node_id FROM wf.workflow_edge WHERE parent_node_id = @ctl AND branch_kind = N''BODY'' ORDER BY child_order ASC;

    DECLARE @cur1 INT = @cur + 1;
    EXEC wf.wf_engine_activate
        @workflow_instance_id = @inst,
        @workflow_node_id = @body,
        @parent_node_execution_id = @repeat_execution_id,
        @iteration_no = @cur1,
        @sequence_index = NULL,
        @parallel_index = NULL;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_engine_on_action_complete]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_engine_on_action_complete]')
GO
IF OBJECT_ID(N'wf.sp_worker_submit_result', N'P') IS NOT NULL
    DROP PROCEDURE wf.sp_worker_submit_result;
IF OBJECT_ID(N'wf.wf_engine_on_action_complete', N'P') IS NOT NULL
    DROP PROCEDURE wf.wf_engine_on_action_complete;
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_engine_on_action_complete
    @action_execution_id BIGINT,
    @result_code INT,
    @output_json json NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inst BIGINT;
    DECLARE @wn BIGINT;
    DECLARE @parent BIGINT;

    SELECT @inst = workflow_instance_id, @wn = workflow_node_id, @parent = parent_node_execution_id
    FROM wf.node_execution WHERE id = @action_execution_id;

    IF @result_code < 0
    BEGIN
        UPDATE wf.node_execution
        SET status = N''FAILED'',
            result_code = @result_code,
            output_json = @output_json,
            ended_at_utc = SYSUTCDATETIME(),
            engine_error_code = @result_code
        WHERE id = @action_execution_id;

        DELETE FROM wf.task_lease WHERE node_execution_id = @action_execution_id;

        UPDATE wf.workflow_instance
        SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME()
        WHERE id = @inst;

        RETURN;
    END

    UPDATE wf.node_execution
    SET status = N''SUCCEEDED'',
        result_code = @result_code,
        output_json = @output_json,
        ended_at_utc = SYSUTCDATETIME()
    WHERE id = @action_execution_id;

    DELETE FROM wf.task_lease WHERE node_execution_id = @action_execution_id;

    IF @parent IS NULL
    BEGIN
        UPDATE wf.workflow_instance SET status = N''COMPLETED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @inst;
        RETURN;
    END

    DECLARE @ptype VARCHAR(32);
    SELECT @ptype = wn.node_type
    FROM wf.node_execution AS ne
    INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
    WHERE ne.id = @parent;

    IF @ptype = N''SEQUENCE''
        EXEC wf.wf_sequence_continue @sequence_execution_id = @parent;

    ELSE IF @ptype = N''PARALLEL''
        EXEC wf.wf_parallel_continue @parallel_execution_id = @parent;

    ELSE IF @ptype IN (N''IF'', N''SWITCH'')
    BEGIN
        UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @parent;
        EXEC wf.wf_engine_on_composite_complete @node_execution_id = @parent;
    END

    ELSE IF @ptype = N''REPEAT''
        EXEC wf.wf_repeat_continue @repeat_execution_id = @parent;

    ELSE IF @ptype = N''WHILE''
        EXEC wf.wf_while_continue @while_execution_id = @parent;

    /* FOREACH arrives with wf_sql_foreach_support.sql; dispatch through the router so
       re-running this base script never drops FOREACH continuation. */
    ELSE IF @ptype = N''FOREACH''
        EXEC wf.wf_foreach_route_continue @foreach_execution_id = @parent;
END;
'
GO

--
-- Create or alter procedure [wf].[sp_worker_submit_result]
--
GO
PRINT (N'Create or alter procedure [wf].[sp_worker_submit_result]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.sp_worker_submit_result
    @node_execution_id BIGINT,
    @worker_id BIGINT,
    @worker_token NVARCHAR(4000),
    @result_code INT,
    @output_json json NULL,
    @accepted BIT OUTPUT,
    @instance_status VARCHAR(32) OUTPUT,
    @next_ready_count INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    SET @accepted = 0;
    SET @next_ready_count = 0;
    SET @instance_status = NULL;

    EXEC wf.wf_worker_authenticate @worker_id = @worker_id, @worker_token = @worker_token;

    BEGIN TRANSACTION;

    DECLARE @lease_worker BIGINT;
    SELECT @lease_worker = worker_id FROM wf.task_lease WITH (UPDLOCK, HOLDLOCK) WHERE node_execution_id = @node_execution_id;

    IF @lease_worker IS NULL OR @lease_worker <> @worker_id
    BEGIN
        ROLLBACK TRANSACTION;
        RETURN;
    END

    DECLARE @cur_status VARCHAR(32);
    SELECT @cur_status = status FROM wf.node_execution WITH (UPDLOCK, HOLDLOCK) WHERE id = @node_execution_id;

    IF @cur_status <> N''RUNNING''
    BEGIN
        ROLLBACK TRANSACTION;
        RETURN;
    END

    EXEC wf.wf_engine_on_action_complete
        @action_execution_id = @node_execution_id,
        @result_code = @result_code,
        @output_json = @output_json;

    SET @accepted = 1;

    SELECT @instance_status = status FROM wf.workflow_instance WHERE id = (SELECT workflow_instance_id FROM wf.node_execution WHERE id = @node_execution_id);

    SELECT @next_ready_count = COUNT(*)
    FROM wf.node_execution
    WHERE workflow_instance_id = (SELECT workflow_instance_id FROM wf.node_execution WHERE id = @node_execution_id)
      AND status = N''READY'';

    COMMIT TRANSACTION;
END;
'
GO

--
-- Create table [wf].[execution_context]
--
PRINT (N'Create table [wf].[execution_context]')
GO
IF OBJECT_ID(N'wf.execution_context', 'U') IS NULL
CREATE TABLE wf.execution_context (
  id bigint IDENTITY,
  node_execution_id bigint NOT NULL,
  context_key nvarchar(256) NOT NULL,
  context_value_json json NULL,
  PRIMARY KEY CLUSTERED (id),
  CONSTRAINT UQ_ec_ne_key UNIQUE (node_execution_id, context_key)
)
ON [PRIMARY]
GO

--
-- Create index [IX_ec_ne] on table [wf].[execution_context]
--
PRINT (N'Create index [IX_ec_ne] on table [wf].[execution_context]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ec_ne' AND object_id = OBJECT_ID(N'wf.execution_context'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'node_execution_id' AND object_id = OBJECT_ID(N'wf.execution_context'))
CREATE INDEX IX_ec_ne
  ON wf.execution_context (node_execution_id)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_ec_ne] on table [wf].[execution_context]
--
PRINT (N'Create foreign key [FK_ec_ne] on table [wf].[execution_context]')
GO
IF OBJECT_ID('wf.FK_ec_ne', 'F') IS NULL
  AND OBJECT_ID('wf.execution_context', 'U') IS NOT NULL
  AND OBJECT_ID('wf.node_execution', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'node_execution_id' AND object_id = OBJECT_ID(N'wf.execution_context'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'id' AND object_id = OBJECT_ID(N'wf.node_execution'))
ALTER TABLE wf.execution_context
  ADD CONSTRAINT FK_ec_ne FOREIGN KEY (node_execution_id) REFERENCES wf.node_execution (id) ON DELETE CASCADE
GO

--
-- Create or alter procedure [wf].[wf_seed_execution_context]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_seed_execution_context]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_seed_execution_context
    @node_execution_id BIGINT,
    @workflow_instance_id BIGINT,
    @workflow_node_id BIGINT,
    @parent_node_execution_id BIGINT NULL,
    @iteration_no INT,
    @sequence_index INT NULL,
    @parallel_index INT NULL
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM wf.execution_context WHERE node_execution_id = @node_execution_id;

    INSERT INTO wf.execution_context (node_execution_id, context_key, context_value_json)
    VALUES (@node_execution_id, N''ctx.iterationNo'', CAST(@iteration_no AS NVARCHAR(32)));

    IF @sequence_index IS NOT NULL
        INSERT INTO wf.execution_context (node_execution_id, context_key, context_value_json)
        VALUES (@node_execution_id, N''ctx.sequenceIndex'', CAST(@sequence_index AS NVARCHAR(32)));

    IF @parallel_index IS NOT NULL
        INSERT INTO wf.execution_context (node_execution_id, context_key, context_value_json)
        VALUES (@node_execution_id, N''ctx.parallelIndex'', CAST(@parallel_index AS NVARCHAR(32)));

    IF @parent_node_execution_id IS NOT NULL
    BEGIN
        DECLARE @prc INT;
        SELECT @prc = result_code FROM wf.node_execution WHERE id = @parent_node_execution_id;
        INSERT INTO wf.execution_context (node_execution_id, context_key, context_value_json)
        VALUES (@node_execution_id, N''ctx.parent.resultCode'', CAST(@prc AS NVARCHAR(32)));
    END
END;
'
GO

--
-- Create or alter function [wf].[wf_json_fragment_from_string]
--
GO
PRINT (N'Create or alter function [wf].[wf_json_fragment_from_string]')
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WITH (NOLOCK) WHERE object_id = OBJECT_ID(N'wf.wf_json_fragment_from_string') AND type IN ('IF', 'FN', 'TF'))
EXEC sp_executesql N'
CREATE OR ALTER FUNCTION wf.wf_json_fragment_from_string(@s NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
    RETURN N''"'' + REPLACE(REPLACE(REPLACE(@s, N''\'', N''\\''), N''"'', N''\"''), CHAR(10), N''\n'') + N''"'';
END;
'
GO

--
-- Create or alter function [wf].[wf_try_task_output_json]
--
GO
PRINT (N'Create or alter function [wf].[wf_try_task_output_json]')
GO
EXEC sp_executesql N'
CREATE OR ALTER FUNCTION wf.wf_try_task_output_json(@workflow_instance_id BIGINT, @node_key NVARCHAR(128), @jsonPath NVARCHAR(4000))
RETURNS NVARCHAR(MAX)
AS
BEGIN
    DECLARE @out NVARCHAR(MAX);
    SELECT TOP (1) @out = CAST(ne.output_json AS NVARCHAR(MAX))
    FROM wf.node_execution AS ne
    INNER JOIN wf.workflow_node AS wn ON wn.id = ne.workflow_node_id
    WHERE ne.workflow_instance_id = @workflow_instance_id
      AND wn.node_key = @node_key
      AND ne.status = N''SUCCEEDED''
    ORDER BY ne.ended_at_utc DESC, ne.id DESC;

    IF @out IS NULL RETURN NULL;

    IF @jsonPath IS NULL OR LTRIM(RTRIM(@jsonPath)) = N'''' RETURN @out;

    IF LEFT(@jsonPath, 1) <> N''$'' SET @jsonPath = N''$.'' + @jsonPath;

    DECLARE @jq NVARCHAR(MAX) = JSON_QUERY(@out, @jsonPath);
    IF @jq IS NOT NULL RETURN @jq;

    DECLARE @jv NVARCHAR(MAX) = JSON_VALUE(@out, @jsonPath);
    IF @jv IS NULL RETURN NULL;

    DECLARE @bi BIGINT = TRY_CONVERT(BIGINT, @jv);
    IF @bi IS NOT NULL AND CAST(@bi AS NVARCHAR(50)) = LTRIM(RTRIM(@jv))
        RETURN CAST(@bi AS NVARCHAR(50));

    RETURN wf.wf_json_fragment_from_string(@jv);
END;
'
GO

--
-- Create or alter procedure [wf].[wf_resolve_token]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_resolve_token]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_resolve_token
    @token NVARCHAR(1024),
    @node_execution_id BIGINT,
    @workflow_instance_id BIGINT,
    @out_fragment NVARCHAR(MAX) OUTPUT,
    @failed BIT OUTPUT,
    @fail_code INT OUTPUT,
    @fail_msg NVARCHAR(1024) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @failed = 0;
    SET @fail_code = NULL;
    SET @fail_msg = NULL;

    IF CHARINDEX(N'' '', @token) > 0 OR CHARINDEX(N''+'', @token) > 0 OR CHARINDEX(N''('', @token) > 0
    BEGIN
        SET @failed = 1;
        SET @fail_code = 10002;
        SET @fail_msg = N''Unsupported placeholder expression.'';
        RETURN;
    END

    IF LEFT(@token, 9) = N''ctx.task.''
    BEGIN
        DECLARE @rest NVARCHAR(1024) = SUBSTRING(@token, 10, 4000);
        DECLARE @dot INT = CHARINDEX(N''.'', @rest);
        DECLARE @nk NVARCHAR(128);
        DECLARE @tail NVARCHAR(1024);

        IF @dot = 0
        BEGIN
            SET @failed = 1;
            SET @fail_code = 10002;
            SET @fail_msg = N''Invalid ctx.task reference.'';
            RETURN;
        END

        SET @nk = LEFT(@rest, @dot - 1);
        SET @tail = SUBSTRING(@rest, @dot + 1, 4000);

        IF @tail = N''resultCode''
        BEGIN
            DECLARE @rc INT = wf.wf_try_task_result_code(@workflow_instance_id, @nk);
            SET @out_fragment = CAST(@rc AS NVARCHAR(32));
            RETURN;
        END

        IF LEFT(@tail, 7) = N''output.''
        BEGIN
            DECLARE @jp NVARCHAR(4000) = SUBSTRING(@tail, 8, 4000);
            DECLARE @jq NVARCHAR(MAX) = wf.wf_try_task_output_json(@workflow_instance_id, @nk, @jp);
            SET @out_fragment = @jq;
            RETURN;
        END

        SET @failed = 1;
        SET @fail_code = 10002;
        SET @fail_msg = N''Unsupported ctx.task tail.'';
        RETURN;
    END

    IF LEFT(@token, 4) = N''ctx.''
    BEGIN
        DECLARE @v NVARCHAR(MAX);
        SELECT @v = wf.wf_json_unbox(CAST(context_value_json AS NVARCHAR(MAX)))
        FROM wf.execution_context
        WHERE node_execution_id = @node_execution_id AND context_key = @token;

        IF @v IS NULL
        BEGIN
            SET @failed = 1;
            SET @fail_code = 10001;
            SET @fail_msg = N''Missing context value for '' + @token;
            RETURN;
        END

        SET @out_fragment = @v;
        RETURN;
    END

    SET @failed = 1;
    SET @fail_code = 10002;
    SET @fail_msg = N''Unsupported token.'';
END;
'
GO

--
-- Create or alter procedure [wf].[wf_resolve_placeholders]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_resolve_placeholders]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_resolve_placeholders
    @text NVARCHAR(MAX),
    @node_execution_id BIGINT,
    @workflow_instance_id BIGINT,
    @resolved NVARCHAR(MAX) OUTPUT,
    @failed BIT OUTPUT,
    @fail_code INT OUTPUT,
    @fail_msg NVARCHAR(1024) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @resolved = @text;
    SET @failed = 0;

    DECLARE @start INT;
    DECLARE @end INT;
    DECLARE @token NVARCHAR(1024);
    DECLARE @frag NVARCHAR(MAX);
    DECLARE @tf BIT;
    DECLARE @fc INT;
    DECLARE @fm NVARCHAR(1024);

    WHILE CHARINDEX(N''${'', @resolved) > 0
    BEGIN
        SET @start = CHARINDEX(N''${'', @resolved);
        SET @end = CHARINDEX(N''}'', @resolved, @start + 2);
        IF @end = 0 BREAK;

        SET @token = SUBSTRING(@resolved, @start + 2, @end - (@start + 2));

        EXEC wf.wf_resolve_token
            @token = @token,
            @node_execution_id = @node_execution_id,
            @workflow_instance_id = @workflow_instance_id,
            @out_fragment = @frag OUTPUT,
            @failed = @tf OUTPUT,
            @fail_code = @fc OUTPUT,
            @fail_msg = @fm OUTPUT;

        IF @tf = 1
        BEGIN
            SET @failed = 1;
            SET @fail_code = @fc;
            SET @fail_msg = @fm;
            RETURN;
        END

        SET @resolved = STUFF(@resolved, @start, @end - @start + 1, ISNULL(@frag, N''null''));
    END
END;
'
GO

--
-- Create or alter procedure [wf].[wf_build_input_json_for_action]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_build_input_json_for_action]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_build_input_json_for_action
    @node_execution_id BIGINT,
    @workflow_instance_id BIGINT,
    @workflow_node_id BIGINT,
    @final_json NVARCHAR(MAX) OUTPUT,
    @failed BIT OUTPUT,
    @fail_code INT OUTPUT,
    @fail_msg NVARCHAR(1024) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @failed = 0;

    DECLARE @template NVARCHAR(MAX) = N''{}'';
    IF EXISTS (SELECT 1 FROM wf.workflow_input_template WHERE workflow_node_id = @workflow_node_id)
        SELECT @template = CAST(template_json AS NVARCHAR(MAX)) FROM wf.workflow_input_template WHERE workflow_node_id = @workflow_node_id;

    DECLARE @cur NVARCHAR(MAX);
    DECLARE @tf BIT;
    DECLARE @fc INT;
    DECLARE @fm NVARCHAR(1024);

    EXEC wf.wf_resolve_placeholders
        @text = @template,
        @node_execution_id = @node_execution_id,
        @workflow_instance_id = @workflow_instance_id,
        @resolved = @cur OUTPUT,
        @failed = @tf OUTPUT,
        @fail_code = @fc OUTPUT,
        @fail_msg = @fm OUTPUT;

    IF @tf = 1
    BEGIN
        SET @failed = 1;
        SET @fail_code = @fc;
        SET @fail_msg = @fm;
        RETURN;
    END

    IF ISJSON(@cur) = 0
    BEGIN
        SET @failed = 1;
        SET @fail_code = 10008;
        SET @fail_msg = N''Template JSON is invalid after placeholder resolution.'';
        RETURN;
    END

    DECLARE @bid BIGINT;
    DECLARE @path NVARCHAR(1024);
    DECLARE @expr NVARCHAR(1024);
    DECLARE @req BIT;

    DECLARE c CURSOR LOCAL FAST_FORWARD FOR
        SELECT id, target_json_path, source_expr, is_required
        FROM wf.workflow_input_binding
        WHERE workflow_node_id = @workflow_node_id
        ORDER BY id;

    OPEN c;
    FETCH NEXT FROM c INTO @bid, @path, @expr, @req;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        DECLARE @frag NVARCHAR(MAX);

        EXEC wf.wf_resolve_placeholders
            @text = @expr,
            @node_execution_id = @node_execution_id,
            @workflow_instance_id = @workflow_instance_id,
            @resolved = @frag OUTPUT,
            @failed = @tf OUTPUT,
            @fail_code = @fc OUTPUT,
            @fail_msg = @fm OUTPUT;

        IF @tf = 1 AND @req = 1
        BEGIN
            SET @failed = 1;
            SET @fail_code = @fc;
            SET @fail_msg = @fm;
            CLOSE c;
            DEALLOCATE c;
            RETURN;
        END

        IF @tf = 1 AND (@req = 0 OR @req IS NULL)
            SET @frag = N''null'';

        IF LEFT(@path, 1) <> N''$'' SET @path = N''$.'' + @path;

        IF ISNULL(@frag, N'''') = N'''' SET @frag = N''null'';

        IF ISJSON(@frag) = 1
            SET @cur = JSON_MODIFY(@cur, @path, JSON_QUERY(@frag));
        ELSE
            SET @cur = JSON_MODIFY(@cur, @path, JSON_QUERY(wf.wf_json_fragment_from_string(@frag)));

        FETCH NEXT FROM c INTO @bid, @path, @expr, @req;
    END

    CLOSE c;
    DEALLOCATE c;

    SET @final_json = @cur;
END;
'
GO

--
-- Create or alter procedure [wf].[wf_engine_activate]
--
GO
PRINT (N'Create or alter procedure [wf].[wf_engine_activate]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.wf_engine_activate
    @workflow_instance_id BIGINT,
    @workflow_node_id BIGINT,
    @parent_node_execution_id BIGINT NULL,
    @iteration_no INT = 0,
    @sequence_index INT NULL,
    @parallel_index INT NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @node_type VARCHAR(32);
    DECLARE @version_id BIGINT;
    DECLARE @node_key NVARCHAR(128);

    SELECT @node_type = node_type, @version_id = workflow_version_id, @node_key = node_key
    FROM wf.workflow_node
    WHERE id = @workflow_node_id;

    IF @node_type IS NULL RETURN;

    IF @node_type = N''ACTION''
    BEGIN
        DECLARE @ne_id BIGINT;
        INSERT INTO wf.node_execution (
            workflow_instance_id, workflow_node_id, status, attempt_no,
            parent_node_execution_id, iteration_no, available_at_utc
        )
        VALUES (
            @workflow_instance_id, @workflow_node_id, N''READY'', 1,
            @parent_node_execution_id, @iteration_no, SYSUTCDATETIME()
        );
        SET @ne_id = SCOPE_IDENTITY();

        EXEC wf.wf_seed_execution_context
            @node_execution_id = @ne_id,
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @workflow_node_id,
            @parent_node_execution_id = @parent_node_execution_id,
            @iteration_no = @iteration_no,
            @sequence_index = @sequence_index,
            @parallel_index = @parallel_index;

        DECLARE @fj NVARCHAR(MAX);
        DECLARE @failed BIT;
        DECLARE @fc INT;
        DECLARE @fm NVARCHAR(1024);

        EXEC wf.wf_build_input_json_for_action
            @node_execution_id = @ne_id,
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @workflow_node_id,
            @final_json = @fj OUTPUT,
            @failed = @failed OUTPUT,
            @fail_code = @fc OUTPUT,
            @fail_msg = @fm OUTPUT;

        IF @failed = 1
        BEGIN
            UPDATE wf.node_execution
            SET status = N''FAILED'',
                engine_error_code = @fc,
                engine_error_message = @fm,
                ended_at_utc = SYSUTCDATETIME()
            WHERE id = @ne_id;

            UPDATE wf.workflow_instance
            SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME()
            WHERE id = @workflow_instance_id;

            RETURN;
        END

        UPDATE wf.node_execution SET input_json = CAST(@fj AS json) WHERE id = @ne_id;
        RETURN;
    END

    /* Composite: create RUNNING execution row */
    DECLARE @pex BIGINT;
    INSERT INTO wf.node_execution (
        workflow_instance_id, workflow_node_id, status, attempt_no,
        parent_node_execution_id, iteration_no, started_at_utc, available_at_utc
    )
    VALUES (
        @workflow_instance_id, @workflow_node_id, N''RUNNING'', 1,
        @parent_node_execution_id, @iteration_no, SYSUTCDATETIME(), SYSUTCDATETIME()
    );
    SET @pex = SCOPE_IDENTITY();

    IF @node_type = N''SEQUENCE''
    BEGIN
        DECLARE @child1 BIGINT;
        SELECT TOP (1) @child1 = child_node_id
        FROM wf.workflow_edge
        WHERE parent_node_id = @workflow_node_id
        ORDER BY child_order ASC;

        IF @child1 IS NULL
        BEGIN
            UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            EXEC wf.wf_engine_on_composite_complete @node_execution_id = @pex;
            RETURN;
        END

        DECLARE @ord INT = 0;
        SELECT TOP (1) @ord = child_order FROM wf.workflow_edge WHERE parent_node_id = @workflow_node_id ORDER BY child_order ASC;

        EXEC wf.wf_engine_activate
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @child1,
            @parent_node_execution_id = @pex,
            @iteration_no = @iteration_no,
            @sequence_index = @ord,
            @parallel_index = NULL;
        RETURN;
    END

    IF @node_type = N''PARALLEL''
    BEGIN
        DECLARE @cid BIGINT;
        DECLARE @pidx INT = 0;
        DECLARE pc CURSOR LOCAL FAST_FORWARD FOR
            SELECT child_node_id
            FROM wf.workflow_edge
            WHERE parent_node_id = @workflow_node_id
            ORDER BY child_order ASC;

        OPEN pc;
        FETCH NEXT FROM pc INTO @cid;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            EXEC wf.wf_engine_activate
                @workflow_instance_id = @workflow_instance_id,
                @workflow_node_id = @cid,
                @parent_node_execution_id = @pex,
                @iteration_no = @iteration_no,
                @sequence_index = NULL,
                @parallel_index = @pidx;

            SET @pidx += 1;
            FETCH NEXT FROM pc INTO @cid;
        END

        CLOSE pc;
        DEALLOCATE pc;
        RETURN;
    END

    IF @node_type = N''IF''
    BEGIN
        DECLARE @cref NVARCHAR(128);
        SELECT @cref = condition_ref_node_key FROM wf.workflow_node WHERE id = @workflow_node_id;

        DECLARE @cond INT = wf.wf_try_task_result_code(@workflow_instance_id, @cref);
        DECLARE @pick VARCHAR(32) = CASE WHEN @cond IS NOT NULL AND @cond <> 0 THEN N''THEN'' ELSE N''ELSE'' END;

        DECLARE @ifchild BIGINT;
        SELECT TOP (1) @ifchild = child_node_id
        FROM wf.workflow_edge
        WHERE parent_node_id = @workflow_node_id AND branch_kind = @pick
        ORDER BY child_order ASC;

        IF @ifchild IS NULL
        BEGIN
            UPDATE wf.node_execution SET status = N''FAILED'', engine_error_code = 10003, engine_error_message = N''Missing IF branch.'', ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @workflow_instance_id;
            RETURN;
        END

        EXEC wf.wf_engine_activate
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @ifchild,
            @parent_node_execution_id = @pex,
            @iteration_no = @iteration_no,
            @sequence_index = NULL,
            @parallel_index = NULL;
        RETURN;
    END

    IF @node_type = N''SWITCH''
    BEGIN
        DECLARE @sref NVARCHAR(128);
        SELECT @sref = switch_ref_node_key FROM wf.workflow_node WHERE id = @workflow_node_id;

        DECLARE @sv INT = wf.wf_try_task_result_code(@workflow_instance_id, @sref);

        DECLARE @swchild BIGINT;
        SELECT TOP (1) @swchild = child_node_id
        FROM wf.workflow_edge
        WHERE parent_node_id = @workflow_node_id AND branch_kind = N''CASE'' AND switch_case_value = @sv
        ORDER BY child_order ASC;

        IF @swchild IS NULL
            SELECT TOP (1) @swchild = child_node_id
            FROM wf.workflow_edge
            WHERE parent_node_id = @workflow_node_id AND branch_kind = N''DEFAULT''
            ORDER BY child_order ASC;

        IF @swchild IS NULL
        BEGIN
            UPDATE wf.node_execution SET status = N''FAILED'', engine_error_code = 10004, engine_error_message = N''Missing SWITCH case.'', ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @workflow_instance_id;
            RETURN;
        END

        EXEC wf.wf_engine_activate
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @swchild,
            @parent_node_execution_id = @pex,
            @iteration_no = @iteration_no,
            @sequence_index = NULL,
            @parallel_index = NULL;
        RETURN;
    END

    IF @node_type = N''REPEAT''
    BEGIN
        DECLARE @rcount INT;
        SELECT @rcount = repeat_count FROM wf.workflow_node WHERE id = @workflow_node_id;

        IF @rcount IS NULL OR @rcount < 1 SET @rcount = 1;

        INSERT INTO wf.loop_state (workflow_instance_id, control_node_id, scope_node_execution_id, current_iteration, repeat_target_count)
        VALUES (@workflow_instance_id, @workflow_node_id, @pex, 0, @rcount);

        DECLARE @body BIGINT;
        SELECT TOP (1) @body = child_node_id FROM wf.workflow_edge WHERE parent_node_id = @workflow_node_id AND branch_kind = N''BODY'' ORDER BY child_order ASC;

        IF @body IS NULL
        BEGIN
            UPDATE wf.node_execution SET status = N''FAILED'', engine_error_code = 10005, ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @workflow_instance_id;
            RETURN;
        END

        EXEC wf.wf_engine_activate
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @body,
            @parent_node_execution_id = @pex,
            @iteration_no = 1,
            @sequence_index = NULL,
            @parallel_index = NULL;
        RETURN;
    END

    IF @node_type = N''WHILE''
    BEGIN
        DECLARE @wbody BIGINT;
        SELECT TOP (1) @wbody = child_node_id FROM wf.workflow_edge WHERE parent_node_id = @workflow_node_id AND branch_kind = N''BODY'' ORDER BY child_order ASC;

        IF @wbody IS NULL
        BEGIN
            UPDATE wf.node_execution SET status = N''FAILED'', engine_error_code = 10006, ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            UPDATE wf.workflow_instance SET status = N''FAILED'', completed_at_utc = SYSUTCDATETIME() WHERE id = @workflow_instance_id;
            RETURN;
        END

        DECLARE @wcref NVARCHAR(128);
        SELECT @wcref = condition_ref_node_key FROM wf.workflow_node WHERE id = @workflow_node_id;

        DECLARE @wcond INT = wf.wf_try_task_result_code(@workflow_instance_id, @wcref);

        IF @wcond IS NULL OR @wcond = 0
        BEGIN
            UPDATE wf.node_execution SET status = N''SUCCEEDED'', ended_at_utc = SYSUTCDATETIME() WHERE id = @pex;
            EXEC wf.wf_engine_on_composite_complete @node_execution_id = @pex;
            RETURN;
        END

        EXEC wf.wf_engine_activate
            @workflow_instance_id = @workflow_instance_id,
            @workflow_node_id = @wbody,
            @parent_node_execution_id = @pex,
            @iteration_no = 1,
            @sequence_index = NULL,
            @parallel_index = NULL;
        RETURN;
    END
END;
'
GO

--
-- Create or alter procedure [wf].[sp_start_workflow_instance]
--
GO
PRINT (N'Create or alter procedure [wf].[sp_start_workflow_instance]')
GO
EXEC sp_executesql N'
CREATE OR ALTER PROCEDURE wf.sp_start_workflow_instance
    @workflow_instance_id BIGINT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @vid BIGINT;
    DECLARE @root BIGINT;

    SELECT @vid = workflow_version_id FROM wf.workflow_instance WHERE id = @workflow_instance_id;
    SELECT @root = root_node_id FROM wf.workflow_version WHERE id = @vid;

    IF @root IS NULL
        THROW 50001, N''Workflow version has no root_node_id.'', 1;

    UPDATE wf.workflow_instance
    SET 
      status = N''RUNNING'', 
      started_at_utc = SYSUTCDATETIME()
    WHERE id = @workflow_instance_id;

    EXEC wf.wf_engine_activate
        @workflow_instance_id = @workflow_instance_id,
        @workflow_node_id = @root,
        @parent_node_execution_id = NULL,
        @iteration_no = 0,
        @sequence_index = NULL,
        @parallel_index = NULL;
END;
'
GO